[
	{
		"codice":"conti",
		"nome": "Conti e depositi",
		"wdg": ["01","02"],
		"voci": [
			{"nome": "Saldo e movimenti","file": "new_movimenti","linkoriginale": "/WEBHT/cc/movimentiConto.do","wdg": ["22"],"status":"ok"},
			{"nome": "Finanziamenti (dettaglio)","file": "finanziamenti","linkoriginale": "/WEBHT/prestitiMutui/dettaglioPrestitiMutui.do","wdg": ["22"],"status":"ok"},
			{"nome": "Finanziamenti (ammortamento)","file": "finanziamenti_ammortamento","linkoriginale": "/WEBHT/prestitiMutui/dettaglioPrestitiMutui.do","wdg": [],"status":"ok"},
			{"nome": "Finanziamenti (preammortamento)","file": "finanziamenti_preammortamento","linkoriginale": "/WEBHT/prestitiMutui/dettaglioPrestitiMutui.do","wdg": [],"status":"ok"},
			{"nome": "Interessi e spese","file": "interessi_e_spese","linkoriginale": "/WEBHT/cc/dettaglioInteressiConto.do","wdg": [],"status":"ok"},
			{"nome": "Pannello Rapporti","file": "pannello_rapporti","linkoriginale": "/WEBHT/cc/pannelloRapporti.do","wdg": [],"status":"ok"},
			{"nome": "Gestione Rapporti","file": "gestione_rapporti","linkoriginale": "/WEBHT/cc/pannelloRapportiModifica.do","wdg": [],"status":"ok"},
			{"nome": "Basta carta","file": "basta_carta","linkoriginale": "/WEBHT/cc/pannelloRapportiModificaPosta.do","wdg": [],"status":"ok"},
			{"nome": "Basta carta","file": "basta_carta","linkoriginale": "/WEBHT/cc/pannelloRapportiModificaPosta.do","wdg": [],"status":"ok"},
			{"nome": "Adeguata Verifica","file": "adeguata_verifica","linkoriginale": "/WEBHT/av/adeguataVerificaLista.do","wdg": [],"status":"ok"},
			{"nome": "Adeguata Verifica Dettaglio","file": "adeguata_verifica_dettaglio","linkoriginale": "/WEBHT/av/adeguataVerificaDettaglio.do","wdg": [],"status":"ok"},
			{"nome": "Adeguata Verifica Modifica","file": "adeguata_verifica_modifica","linkoriginale": "/WEBHT/av/adeguataVerificaMOdifica.do","wdg": [],"status":"ok"},
			{"nome": "Bilancio mensile (senza movimenti)","file": "bilancio_mensile","linkoriginale": "/WEBHT/cc/bilancioMensile.do","wdg": ["01","02","03"],"status":"ok"},
			{"nome": "Bilancio mensile (con movimenti)","file": "bilancio_mensile2","linkoriginale": "/WEBHT/cc/bilancioMensile.do","wdg": ["01","02","03"],"status":"ok"},
			{"nome": "Gestione categorie","file": "gestione_categorie","linkoriginale": "/WEBHT/cc/gestioneCategorie.do","wdg": ["01","02","03"],"status":"ok"},
			{"nome": "Creazione categorie","file": "creazione_categorie","linkoriginale": "/WEBHT/cc/creazioneCategorie.do","wdg": [],"status":"ok"},
			{"nome": "Vincola","file": "vincola","linkoriginale": "/WEBHT/cd/contoDepositoVincolaRiepilogo.do","wdg": ["05","02","03","04"],"status":"ok"},
			{"nome": "I tuoi vincoli","file": "i_tuoi_vincoli","linkoriginale": "/WEBHT/cd/contoDepositoITuoiVincoli.do","wdg": ["05","02","03"],"status":"ok"},
			{"nome": "I tuoi vincoli (svincola)","file": "i_tuoi_vincoli_svincola","linkoriginale": "/WEBHT/cd/contoDepositoSvincolaConferma.do","wdg": ["05","02","03"],"status":"ok"},
			{"nome": "Conti di appoggio","file": "conti_di_appoggio","linkoriginale": "/WEBHT/cd/listaContiAppoggio.do","wdg": ["05","02","03"],"status":"ok"},
			{"nome": "Assicurazioni casa","file": "assicurazioni_casa","linkoriginale": "/WEBHT/cd/listaContiAppoggio.do","wdg": ["05","02","03"],"status":"new"},
			{"nome": "Assicurazioni viaggi","file": "assicurazioni_viaggi","linkoriginale": "/WEBHT/cd/listaContiAppoggio.do","wdg": ["05","02","03"],"status":"new"},
			{"nome": "Assicurazioni veicoli","file": "assicurazioni_veicoli","linkoriginale": "/WEBHT/cd/listaContiAppoggio.do","wdg": ["05","02","03"],"status":"new"},
			{"nome": "Scadenza polizze","file": "scadenza_polizze","linkoriginale": "/WEBHT/cd/listaContiAppoggio.do","wdg": ["05","02","03"],"status":"new"},
			{"nome": "Scadenza polizze (nuova)","file": "scadenza_polizze_nuova","linkoriginale": "/WEBHT/cd/listaContiAppoggio.do","wdg": ["05","02","03"],"status":"new"},
			{"nome": "Scadenza polizze (cancella)","file": "scadenza_polizze_cancella","linkoriginale": "/WEBHT/cd/listaContiAppoggio.do","wdg": ["05","02","03"],"status":"new"},
			{"nome": "Numeri e assistenza","file": "numeri_assistenza","linkoriginale": "/WEBHT/cd/listaContiAppoggio.do","wdg": ["05","02","03"],"status":"new"}
		]
	},
	{
		"codice": "pagamenti",
		"nome": "Pagamenti",
		"wdg": ["06","02"],
		"voci": [
			{"nome": "Ultime disposizioni","file": "ultime_disposizioni","linkoriginale": "/WEBHT/pagamenti/ultimeDisposizioni.do","wdg": [],"status":"ok"},
			{"nome": "Gestione beneficiari","file": "gestione_beneficiari","linkoriginale": "/WEBHT/pagamenti/listaBeneficiari.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Gestione beneficiari (modifica - Step 1)","file": "gestione_beneficiari_modifica","linkoriginale": "/WEBHT/pagamenti/listaBeneficiari.do","wdg": ["06","02"],"status":"ok"},
			{"nome": "Gestione beneficiari (modifica - Step 2 - otp)","file": "gestione_beneficiari_modifica_step2","linkoriginale": "/WEBHT/pagamenti/listaBeneficiari.do","wdg": ["06","02"],"status":"ok"},
			{"nome": "Gestione beneficiari (modifica - Step 3)","file": "gestione_beneficiari_modifica_step3","linkoriginale": "/WEBHT/pagamenti/listaBeneficiari.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Gestione beneficiari (nuovo)","file": "gestione_beneficiari_nuovo","linkoriginale": "/WEBHT/pagamenti/listaBeneficiari.do","wdg": ["06","02"],"status":"ok"},
			{"nome": "Gestione beneficiari (elimina - Step 1)","file": "gestione_beneficiari_elimina","linkoriginale": "/WEBHT/pagamenti/listaBeneficiari.do","wdg": ["06","02"],"status":"ok"},
			{"nome": "Gestione beneficiari (elimina - Step 2)","file": "gestione_beneficiari_elimina_step2","linkoriginale": "/WEBHT/pagamenti/listaBeneficiari.do","wdg": ["06","02"],"status":"ok"},
			{"nome": "Bonifico ordinario (Step 1)","file": "bonifico_ordinario","linkoriginale": "/WEBHT/pagamenti/bonificoSepa.do","wdg": ["07","02","03"],"status":"ok"},
			{"nome": "Bonifico ordinario (Step 2)","file": "bonifico_ordinario_step2","linkoriginale": "/WEBHT/pagamenti/bonificoSepa.do","wdg": ["07","02","03"],"status":"ok"},
			{"nome": "Bonifico ordinario (Step 2 - otp)","file": "bonifico_ordinario_step2b","linkoriginale": "/WEBHT/pagamenti/bonificoSepa.do","wdg": ["07","02","03"],"status":"ok"},
			{"nome": "Bonifico ordinario (Step 3)","file": "bonifico_ordinario_step3","linkoriginale": "/WEBHT/pagamenti/bonificoSepa.do","wdg": ["07","02","03"],"status":"ok"},
			{"nome": "Bonifico ordinario (revoca - Step 1)","file": "bonifico_ordinario_revoca","linkoriginale": "/WEBHT/pagamenti/bonificoSepa.do","wdg": ["07","02","03"],"status":"ok"},
			{"nome": "Bonifico ordinario (revoca - Step 2)","file": "bonifico_ordinario_revoca_conferma","linkoriginale": "/WEBHT/pagamenti/bonificoSepa.do","wdg": ["07","02","03"],"status":"ok"},
			{"nome": "Bonifico per detrazioni (Step 1)","file": "bonifico_per_detrazioni","linkoriginale": "/WEBHT/pagamenti/bonificoDetrazione.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bonifico per detrazioni (Step 2)","file": "bonifico_per_detrazioni_step2","linkoriginale": "/WEBHT/pagamenti/bonificoDetrazione.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bonifico estero","file": "bonifico_estero","linkoriginale": "/WEBHT/pagamenti/bonificoEstero.do","wdg": ["07","02","03"],"status":"ok"},
			{"nome": "Bonifico estero (step 2)","file": "bonifico_estero_step2","linkoriginale": "/WEBHT/pagamenti/bonificoEstero.do","wdg": ["07","02","03"],"addinfo": "(new)","status":"ok"},
			{"nome": "Bonifico estero (otp - step 2b)","file": "bonifico_estero_step2b","linkoriginale": "/WEBHT/pagamenti/bonificoEstero.do","wdg": ["07","02","03"],"addinfo": "(new)","status":"ok"},
			{"nome": "Bonifico estero (esito - step 3)","file": "bonifico_estero_step3","linkoriginale": "/WEBHT/pagamenti/bonificoEstero.do","wdg": ["07","02","03"],"addinfo": "(new)","status":"ok"},
			{"nome": "Trasferimento tra conti (senza 2&deg; conto)","file": "trasferimento_tra_conti","linkoriginale": "/WEBHT/pagamenti/trasferimentoConti.do","wdg": ["08","02"],"status":"ok"},
			{"nome": "Trasferimento tra conti (con  2&deg; conto)","file": "trasferimento_tra_conti_2","linkoriginale": "/WEBHT/pagamenti/trasferimentoConti.do","wdg": ["08","02"],"status":"ok"},
			{"nome": "Trasferimento tra conti (esito)","file": "trasferimento_tra_conti_esito","linkoriginale": "/WEBHT/pagamenti/trasferimentoConti.do","wdg": ["08","02"],"status":"ok"},
			{"nome": "Ricarica telefonica(Step 1)","file": "ricarica_telefonica","linkoriginale": "/WEBHT/pagamenti/ricaricaDati.do","wdg": ["09","02","03"],"status":"ok"},
			{"nome": "Ricarica telefonica (Step 2)","file": "ricarica_telefonica_2","linkoriginale": "/WEBHT/pagamenti/ricaricaDati.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Ricarica telefonica (Step 3)","file": "ricarica_telefonica_3","linkoriginale": "/WEBHT/pagamenti/ricaricaDati.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Ricarica telefonica (Step 4)","file": "ricarica_telefonica_4","linkoriginale": "/WEBHT/pagamenti/ricaricaDati.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Pagamento F24 Accesso","file": "pagamento_f24","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [],"status":"ok",
				"voci" : [
					{"nome": "Introduzione","file": "pagamento_f24_intro","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_no_frameset","status":" ok"},
					{"nome": "F24 modulo","file": "pagamento_f24_modulo","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "F24 modulo (Step 2)","file": "pagamento_f24_modulo_step2","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "F24 modulo (Step 2 - Bozza)","file": "pagamento_f24_modulo_step2_bozza","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "F24 modulo (Step 3)","file": "pagamento_f24_modulo_step3_esito_positivo","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "F24 semplificato","file": "pagamento_f24_semplificato","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "F24 semplificato (Step 2)","file": "pagamento_f24_semplificato_step2","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "F24 semplificato (Step 3)","file": "pagamento_f24_semplificato_step3","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "F24 semplificato (Step 4)","file": "pagamento_f24_semplificato_step4","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "F24 semplificato (Step 5)","file": "pagamento_f24_semplificato_step5","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Modulo F24 Elementi identificativi","file": "pagamento_f24_elem_identificativi","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Modulo F24 Elementi identificativi (Step 2)","file": "pagamento_f24_elem_identificativi_step2","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Modulo F24 Elementi identificativi (Step 3)","file": "pagamento_f24_elem_identificativi_step3","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Modulo F24 Elementi identificativi (popup)","file": "pagamento_f24_elem_identificativi_popup_errore","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Modulo F24 Accise","file": "pagamento_f24_accise","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Modulo F24 Accise (Step 2)","file": "pagamento_f24_accise_step2","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Modulo F24 Accise (Step 3)","file": "pagamento_f24_accise_step3","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Riepilogo F24","file": "pagamento_f24_riepilogo","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Lista contribuenti","file": "pagamento_f24_lista","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Popup","file": "","linkoriginale": "","wdg": [],
						"voci" : [
							{"linkdiretto": "true", "nome": "Codice tributo","pag": "", "pag_new": "/template/f24_pop_codice_tributo.php","status":" ok"},
							{"linkdiretto": "true", "nome": "Codice tributo (esito ricerca)","pag": "", "pag_new": "/template/f24_pop_codice_tributo_esito_ricerca.php","status":" ok"},
							{"linkdiretto": "true", "nome": "Codice identificativo","pag": "", "pag_new": "/template/f24_pop_codice_identificativo.php","status":" ok"},
							{"linkdiretto": "true", "nome": "Codice identificativo (risultato)","pag": "", "pag_new": "/template/f24_pop_codice_identificativo_risultato.php","status":" ok"},
							{"linkdiretto": "true", "nome": "Semplificato","pag": "", "pag_new": "/template/f24_pop_f24_semplificato.php","status":" ok"},
							{"linkdiretto": "true", "nome": "Codice imu","pag": "", "pag_new": "/template/f24_pop_imu.php","status":" ok"},
							{"linkdiretto": "true", "nome": "Codice inps","pag": "", "pag_new": "/template/f24_popup_inps.php","status":" ok"}
								]
							},

					{"nome": "F23 modulo","file": "pagamento_f23_modulo","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "F23 modulo","file": "pagamento_f23_modulo_step2","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "F23 modulo","file": "pagamento_f23_modulo_esito_positivo","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"},
					{"nome": "Riepilogo F23","file": "pagamento_f23_riepilogo","linkoriginale": "/WEBHT/pagamenti/f24.do","wdg": [], "basestrutt": "f24_frameset","status":" ok"}
						]
			},
			{"nome": "Bollettino Postale","file": "bollettino_postale","linkoriginale": "/WEBHT/pagamenti/bollettiniPostali.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollettino Postale - premarcato (Step 1)","file": "bollettino_postale_premarcato","linkoriginale": "/WEBHT/pagamenti/bollettiniPostaliCompilazione.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollettino Postale - premarcato (Step 2)","file": "bollettino_postale_premarcato_step2","linkoriginale": "/WEBHT/pagamenti/bollettiniPostaliCompilazione.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollettino Postale - premarcato (Step 3)","file": "bollettino_postale_premarcato_step3","linkoriginale": "/WEBHT/pagamenti/bollettiniPostaliCompilazione.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollettino Postale - premarcato - revoca (Step 1)","file": "bollettino_postale_premarcato_revoca_step1","linkoriginale": "/WEBHT/pagamenti/dettaglioDisposizione.do?codice=IH7132047162&tipoOperazione=revoca","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollettino Postale - premarcato - revoca (Step 2)","file": "bollettino_postale_premarcato_revoca_step2","linkoriginale": "/WEBHT/pagamenti/dettaglioDisposizione.do?codice=IH7132047162&tipoOperazione=revoca","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollettino Postale - bianco (Step 1)","file": "bollettino_postale_bianco","linkoriginale": "/WEBHT/pagamenti/bollettiniPostaliCompilazione.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollettino Postale - bianco (Step 2)","file": "bollettino_postale_bianco_step2","linkoriginale": "/WEBHT/pagamenti/bollettiniPostaliCompilazione.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollettino Postale - bianco (Step 3)","file": "bollettino_postale_bianco_step3","linkoriginale": "/WEBHT/pagamenti/bollettiniPostaliCompilazione.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollettino MAV (Step 1)","file": "bollettino_mav","linkoriginale": "/WEBHT/pagamenti/mav.do","wdg":["06","02","03"],"status":"ok"},
			{"nome": "Bollettino MAV (Step 2)","file": "bollettino_mav_step2","linkoriginale": "/WEBHT/pagamenti/mav.do","wdg":["06","02","03"],"status":"ok"},
			{"nome": "Bollettino MAV (Step 3)","file": "bollettino_mav_step3","linkoriginale": "/WEBHT/pagamenti/mav.do","wdg":["06","02","03"],"status":"ok"},
			{"nome": "Bollettino RAV (Step 1)","file": "bollettino_rav","linkoriginale": "/WEBHT/pagamenti/rav.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bollettino RAV (Step 2)","file": "bollettino_rav_step2","linkoriginale": "/WEBHT/pagamenti/rav.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bollettino RAV (Step 3)","file": "bollettino_rav_step3","linkoriginale": "/WEBHT/pagamenti/rav.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bollettino RAV - revoca (Step 1)","file": "bollettino_rav_revoca_step1","linkoriginale": "/WEBHT/pagamenti/rav.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bollettino RAV - revoca (Step 2)","file": "bollettino_rav_revoca_step2","linkoriginale": "/WEBHT/pagamenti/rav.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Coordinate IBAN","file": "coordinate_iban","linkoriginale": "/WEBHT/serviziPerTe/coordinateIban.do","wdg": [],"status":"ok"},
			{"nome": "Utenze","file": "utenze","linkoriginale": "/WEBHT/pagamenti/bolletta.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Richiesta Voucher Inps","file": "buoniinps","linkoriginale": "/WEBHT/pagamenti/buoniInps.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Domiciliazioni","file": "domiciliazioni","linkoriginale": "/WEBHT/cc/delegheRid.do","wdg": [],"status":"ok"},
			{"nome": "Domiciliazioni (lista)","file": "domiciliazioni2","linkoriginale": "/WEBHT/cc/delegheRid.do","wdg": [],"status":"ok"},
			{"nome": "Domiciliazioni (lista - nuovo mandato)","file": "domiciliazioni3","linkoriginale": "/WEBHT/cc/delegheRid.do","wdg": [],"status":"ok"},
			{"nome": "Domiciliazioni (lista - gestione mandato)","file": "domiciliazioni4","linkoriginale": "/WEBHT/cc/delegheRid.do","wdg": [],"status":"ok"},
			{"nome": "Domiciliazioni (gestione mandato caso senza mandati)","file": "gestione_no_mandati","linkoriginale": "/WEBHT/cc/delegheRid.do","wdg": [],"status":"ok"},
			{"nome": "Domiciliazioni (lista - nuovo mandato - Step 2)","file": "domiciliazioni3_step2","linkoriginale": "/WEBHT/cc/delegheRid.do","wdg": [],"status":"ok"},
			{"nome": "Domiciliazioni (lista - nuovo mandato - Step 3)","file": "domiciliazioni3_step3","linkoriginale": "/WEBHT/cc/delegheRid.do","wdg": [],"status":"ok"},
			{"nome": "Domiciliazioni dettaglio mandato","file": "domiciliazioni_dettaglio","linkoriginale": "/WEBHT/cc/delegheRid.do","wdg": [],"status":"ok"},
			{"nome": "Domiciliazioni lista addebiti","file": "domiciliazioni_lista_addebiti","linkoriginale": "/WEBHT/cc/delegheRid.do","wdg": [],"status":"ok"},
			{"nome": "Domiciliazioni modifica conto di addebito","file": "domiciliazioni_modifica_conto","linkoriginale": "/WEBHT/cc/delegheRid.do","wdg": [],"status":"ok"},
			{"nome": "Assegni (senza assegni)","file": "assegni","linkoriginale": "/WEBHT/cc/statoAssegni.do","wdg": [],"status":"ok"},
			{"nome": "Assegni (senza assegni)","file": "assegni","linkoriginale": "/WEBHT/cc/statoAssegni.do","wdg": [],"status":"ok"},
			{"nome": "Assegni (con assegni)","file": "assegni2","linkoriginale": "/WEBHT/cc/statoAssegni.do","wdg": [],"status":"ok"},
			{"nome": "Accredito stipendio (Step 1)","file": "accredito_stipendio","linkoriginale": "/WEBHT/cc/accreditoStipendio.do","wdg": [],"status":"ok"},
			{"nome": "Accredito stipendio (Step 2)","file": "accredito_stipendio_2","linkoriginale": "/WEBHT/cc/accreditoStipendio.do","wdg": [],"status":"ok"},
			{"nome": "Accredito stipendio (Step 3)","file": "accredito_stipendio_3","linkoriginale": "/WEBHT/cc/accreditoStipendio.do","wdg": [],"status":"ok"},
			{"nome": "Mediaset Premium (Step 1)","file": "mediaset_premium","linkoriginale": "/WEBHT/pagamenti/ricaricaMediaset.do","wdg": [],"status":"ok"},
			{"nome": "Mediaset Premium (Step 2)","file": "mediaset_premium_step2","linkoriginale": "/WEBHT/pagamenti/ricaricaMediaset.do","wdg": [],"status":"ok"},
			{"nome": "Mediaset Premium (Step 3)","file": "mediaset_premium_step3","linkoriginale": "/WEBHT/pagamenti/ricaricaMediaset.do","wdg": [],"status":"ok"},
			{"nome": "Mediaset Premium (Step 4)","file": "mediaset_premium_step4","linkoriginale": "/WEBHT/pagamenti/ricaricaMediaset.do","wdg": [],"status":"ok"},
			{"nome": "Bollo Auto (Step 1)","file": "bollo_auto","linkoriginale": "/WEBHT/pagamenti/bolloAuto.do","wdg": [],"status":"ok"},
			{"nome": "Bollo Auto (Step 2)","file": "bollo_auto_step2","linkoriginale": "/WEBHT/pagamenti/bolloAuto.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollo Auto (Step 3)","file": "bollo_auto_step3","linkoriginale": "/WEBHT/pagamenti/bolloAuto.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Bollettino Freccia (Step 1)","file": "bollettino_freccia","linkoriginale": "/WEBHT/pagamenti/freccia.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bollettino Freccia (Step 2)","file": "bollettino_freccia_step2","linkoriginale": "/WEBHT/pagamenti/freccia.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bollettino Freccia (Step 3)","file": "bollettino_freccia_step3","linkoriginale": "/WEBHT/pagamenti/freccia.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bollettino Freccia - revoca (Step 1)","file": "bollettino_freccia_revoca_step1","linkoriginale": "/WEBHT/pagamenti/freccia.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bollettino Freccia - revoca (Step 2)","file": "bollettino_freccia_revoca_step2","linkoriginale": "/WEBHT/pagamenti/freccia.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Tasse universitarie","file": "tasse_universitarie","linkoriginale": "/WEBHT/pagamenti/tasseUniversita.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Bonifico ripetitivo (Step 1)","file": "bonifico_ripetitivo","linkoriginale": "/WEBHT/pagamenti/bonificoContinuativoCompilazione.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bonifico ripetitivo (Step 2)","file": "bonifico_ripetitivo_step2","linkoriginale": "/WEBHT/pagamenti/bonificoContinuativoCompilazione.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bonifico ripetitivo (Step 3)","file": "bonifico_ripetitivo_step3","linkoriginale": "/WEBHT/pagamenti/bonificoContinuativoCompilazione.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Bonifico ripetitivo (Step 4)","file": "bonifico_ripetitivo_step4","linkoriginale": "/WEBHT/pagamenti/bonificoContinuativoCompilazione.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Revoca di bonifico ripetitivo (Step 1)","file": "bonifico_ripetitivo_revoca_step1","linkoriginale": "/WEBHT/pagamenti/bonificoContinuativoConfermaRevoca.do?selezionato=1238004&statoBonificoContinuativo=A","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Revoca di bonifico ripetitivo (Step 2)","file": "bonifico_ripetitivo_revoca_step2","linkoriginale": "/WEBHT/pagamenti/bonificoContinuativoConfermaRevoca.do?selezionato=1238004&statoBonificoContinuativo=A","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "Lista bonifici ripetitivi","file": "bonifici_ripetitivi_lista","linkoriginale": "/WEBHT/pagamenti/bonificoContinuativoLista.do","wdg": ["06","02","03"],"status":"ok"},
			{"nome": "CBILL - pagoPA","file": "cbill_pagopa","linkoriginale": "/WEBHT/pagamenti/cbill.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "CBILL - pagoPA (Step 2)","file": "cbill_pagopa_step2","linkoriginale": "/WEBHT/pagamenti/cbill.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "CBILL - pagoPA (Step 3)","file": "cbill_pagopa_step3","linkoriginale": "/WEBHT/pagamenti/cbill.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "CBILL - pagoPA - revoca (Step 1)","file": "cbill_pagopa_revoca_step1","linkoriginale": "/WEBHT/pagamenti/cbill.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "CBILL - pagoPA - revoca (Step 2)","file": "cbill_pagopa_revoca_step2","linkoriginale": "/WEBHT/pagamenti/cbill.do","wdg": ["06","02","10"],"status":"ok"},
			{"nome": "Equitalia - Pagamenti","file": "equitalia_pagamenti","linkoriginale": "/WEBHT/pagamenti/cbillListaPagamenti.do","wdg": ["06","02","10"],"addinfo": "(new)","status":"ok"}
		]
	},
	{
		"codice": "carte",
		"nome": "Carte",
		"wdg": ["11","02"],
		"voci": [
			{"nome": "Le mie carte","file": "le_mie_carte","linkoriginale": "/WEBHT/cartaConto/riepilogoCartaConto.do","wdg": [],"status":"ok"},
			{"nome": "Le mie carte (dettaglio)","file": "le_mie_carte_dettaglio","linkoriginale": "/WEBHT/cartaConto/dettaglioCarta.do","wdg": [],"status":"ok"},
			{"nome": "Movimenti","file": "movimenti_carte","linkoriginale": "/WEBHT/cartaConto/movimenti.do","wdg": [],"status":"ok"},
			{"nome": "Ricarica Carta (lista carte)","file": "ricarica_carta","linkoriginale": "/WEBHT/cartaConto/ricaricaCarta.do","wdg": [],"status":"ok"},
			{"nome": "Ricarica Carta (Step 2)","file": "ricarica_carta_step2","linkoriginale": "/WEBHT/cartaConto/ricaricaCartaDati.do","wdg": [],"status":"ok"},
			{"nome": "Ricarica Carta (Step 3)","file": "ricarica_carta_step3","linkoriginale": "/WEBHT/cartaConto/ricaricaCartaDati.do","wdg": [],"status":"ok"},
			{"nome": "Ricarica Carta (Step 4)","file": "ricarica_carta_step4","linkoriginale": "/WEBHT/cartaConto/ricaricaCartaDati.do","wdg": [],"status":"ok"},
			{"nome": "Scarica Carta","file": "scarica_carta","linkoriginale": "/WEBHT/cartaConto/scaricaCarta.do","wdg": [],"status":"ok"},
			{"nome": "Scarica Carta (Step 2)","file": "scarica_carta_step2","linkoriginale": "/WEBHT/cartaConto/scaricaCartaDati.do","wdg": [],"status":"ok"},
			{"nome": "Scarica Carta (Step 3)","file": "scarica_carta_step3","linkoriginale": "/WEBHT/cartaConto/scaricaCartaDati.do","wdg": [],"status":"ok"},
			{"nome": "Scarica Carta (Step 4)","file": "scarica_carta_step4","linkoriginale": "/WEBHT/cartaConto/scaricaCartaDati.do","wdg": [],"status":"ok"},
			{"nome": "Ricarica automatica","file": "ricarica_automatica","linkoriginale": "/WEBHT/cartaConto/autoricarica.do","wdg": [],"status":"ok"},
			{"nome": "Ricarica automatica 2","file": "ricarica_automatica2","linkoriginale": "/WEBHT/cartaConto/autoricarica.do","wdg": [],"status":"ok"},
			{"nome": "Ricarica automatica (tempo)","file": "ricarica_automatica_tempo","linkoriginale": "/WEBHT/cartaConto/autoricaricaTempo.do","wdg": [],"status":"ok"},
			{"nome": "Ricarica automatica (tempo - conferma)","file": "ricarica_automatica_tempo_conferma","linkoriginale": "/WEBHT/cartaConto/autoricaricaTempoConferma.do","wdg": [],"status":"ok"},
			{"nome": "Ricarica automatica (soglia)","file": "ricarica_automatica_soglia","linkoriginale": "/WEBHT/cartaConto/autoricaricaSoglia.do","wdg": [],"status":"ok"},
			{"nome": "Ricarica automatica (soglia - conferma)","file": "ricarica_automatica_soglia_conferma","linkoriginale": "/WEBHT/cartaConto/autoricaricaTempoConferma.do","wdg": [],"status":"ok"},
			{"nome": "Cambio PIN carta","file": "cambio_pin_carta","linkoriginale": "/WEBHT/cartaConto/cambioPinCarta.do","wdg": [],"status":"ok"},
			{"nome": "Cambio PIN carta (Step 2)","file": "cambio_pin_carta_step2","linkoriginale": "/WEBHT/cartaConto/cambioPinCarta.do","wdg": [],"status":"ok"},
			{"nome": "Cambio PIN carta - otp (Step 3)","file": "cambio_pin_carta_step3","linkoriginale": "/WEBHT/cartaConto/cambioPinCarta.do","wdg": [],"status":"ok"},
			{"nome": "Cambio PIN carta (Step 4)","file": "cambio_pin_carta_step4","linkoriginale": "/WEBHT/cartaConto/cambioPinCarta.do","wdg": [],"status":"ok"},
			{"nome": "Pannello controllo","file": "pannello_controllo","linkoriginale": "/WEBHT/cartaConto/pannelloControllo.do","wdg": [],"status":"ok"},
			{"nome": "Layout bancomat (Step 1)","file": "layout_bancomat","linkoriginale": "/WEBHT/carte/cartaDaPersonalizzareSeleziona.do","wdg": ["02"],"addinfo": "(new)","status":"ok"},
			{"nome": "Layout bancomat (Step 2)","file": "layout_bancomat_step2","linkoriginale": "/WEBHT/carte/cartaDaPersonalizzareSeleziona.do","wdg": ["02"],"addinfo": "(new)","status":"ok"},
			{"nome": "Portale CartaSi","file": "cartasi","linkoriginale": "/WEBHT/cc/xxx.do","wdg": ["02","03"],"addinfo": "(new)","status":"ok"},
			{"nome": "Ricarica Postepay","file": "ricarica_postepay_step1","linkoriginale": "/WEBHT/cartaConto/ricaricaCarta.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Ricarica Postepay (Step 2)","file": "ricarica_postepay_step2","linkoriginale": "","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Ricarica Postepay (otp - Step 2)","file": "ricarica_postepay_step2b","linkoriginale": "","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Ricarica Postepay (Step 3)","file": "ricarica_postepay_step3","linkoriginale": "","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Prelievo Cardless (attivazione)","file": "prelievo_cardless_attivazione","linkoriginale": "/WEBHT/carte/prelievoCardless.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Prelievo Cardless (Step 1)","file": "prelievo_cardless_step1","linkoriginale": "","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Prelievo Cardless (Step 2)","file": "prelievo_cardless_step2","linkoriginale": "","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Prelievo Cardless (Step 3)","file": "prelievo_cardless_step3","linkoriginale": "","wdg": [],"addinfo": "(new)","status":"ok"}
		]
	},
	{
		"codice": "alert",
		"nome": "Alert",
		"wdg": ["12","02","03"],
		"voci": [
			{"nome": "Pannello Alert","file": "pannello_alert","linkoriginale": "/WEBHT/sm/riepilogo.do","wdg": [],"status":"ok"},
			{"nome": "Pannello Alert (caso complesso)","file": "pannello_alert2","linkoriginale": "/WEBHT/sm/riepilogo.do","wdg": [],"status":"ok"},
			{"nome": "Aderisci a YouAlert","file": "aderisci_a_youalert","linkoriginale": "/WEBHT/sm/attivazione.do","wdg": ["12","02"],"addinfo": "(alternativo)","status":"ok"},
			{"nome": "Aderisci a YouAlert (Step 2)","file": "aderisci_a_youalert_step2","linkoriginale": "/WEBHT/sm/attivazione.do","wdg": ["12","02"],"addinfo": "(alternativo)","status":"ok"},
			{"nome": "Info bonifico","file": "info_bonifico","linkoriginale": "/WEBHT/sm/xxx.do","wdg": ["12","02"],"addinfo": "(new)","status":"ok"},
			{"nome": "Info ricarica","file": "info_ricarica","linkoriginale": "/WEBHT/sm/xxx.do","wdg": ["12","02"],"addinfo": "(new)","status":"ok"},
			{"nome": "Info carte","file": "info_carte","linkoriginale": "/WEBHT/sm/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Info carte (elimina)","file": "info_carte_elimina","linkoriginale": "/WEBHT/sm/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Info conto","file": "info_conto","linkoriginale": "/WEBHT/sm/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Info dossier","file": "info_dossier","linkoriginale": "/WEBHT/sm/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Info titoli","file": "info_titoli","linkoriginale": "/WEBHT/sm/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Info titoli (elimina)","file": "info_titoli_elimina","linkoriginale": "/WEBHT/sm/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Info fondi","file": "info_fondi","linkoriginale": "/WEBHT/sm/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Cambi e indici","file": "cambi_indici","linkoriginale": "/WEBHT/sm/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Recedi","file": "recedi","linkoriginale": "/WEBHT/sm/xxx.do","wdg": ["12","02"],"addinfo": "(new)","status":"ok"}
		]
	},
	{
		"codice": "posta",
		"nome": "Posta personale",
		"wdg": ["13","14","02"],
		"voci": [
			{"nome": "Posta in arrivo","file": "posta_in_arrivo","linkoriginale": "/WEBHT/postaPersonale/nuoviDocumenti.do","wdg": ["13","14","02","03"],"status":"ok"},
			{"nome": "Info posta","file": "info_posta","linkoriginale": "/WEBHT/postaPersonale/vediAllarmiRapporti.do","wdg": [],"status":"ok"},
			{"nome": "Archivio","file": "archivio","linkoriginale": "/WEBHT/postaPersonale/archivio.do","wdg": [],"status":"ok"},
			{"nome": "Archivio 2","file": "archivio_2","linkoriginale": "/WEBHT/postaPersonale/archivio.do","wdg": [],"status":"ok"},
			{"nome": "Contratti e Proposte","file": "contratti_e_proposte","linkoriginale": "/WEBHT/postaPersonale/richieste.do","wdg": [],"status":"ok"},
			{"nome": "Richiesta finanziamento","file": "richiesta_finanziamento","linkoriginale": "/WEBHT/finanziamento/richiestaFinanziamento.do","wdg": [],"status":"ok"},
			{"nome": "Richiesta finanziamento intestazione","file": "richiesta_finanziamento_int","linkoriginale": "/WEBHT/finanziamento/richiestaFinanziamentoIntestazone.do","wdg": [],"status":"ok"},
			{"nome": "Richiesta finanziamento intestazione (step 2)","file": "richiesta_finanziamento_int2","linkoriginale": "/WEBHT/finanziamento/richiestaFinanziamentoIntestazone.do","wdg": [],"status":"ok"},
			{"nome": "Richiesta finanziamento intestazione (step 3)","file": "richiesta_finanziamento_int3","linkoriginale": "/WEBHT/finanziamento/richiestaFinanziamentoDocumenti.do","wdg": [],"status":"ok"},
			{"nome": "Richiesta finanziamento intestazione (step 4)","file": "richiesta_finanziamento_int4","linkoriginale": "/WEBHT/finanziamento/richiestaFinanziamentoDocumenti.do","wdg": [],"status":"ok"},
			{"nome": "Contratti e Proposte","file": "contratti_e_proposte2","linkoriginale": "/WEBHT/postaPersonale/contrattiProposte.do","wdg": [],"status":"ok"},
			{"nome": "Posta in arrivo","file": "posta_in_arrivo_new","linkoriginale": "","wdg": ["13","14","02","03"],"addinfo": "(new)","status":"ko"},
			{"nome": "Ricerca in archivio","file": "ricerca_in_archivio_new","linkoriginale": "","wdg": ["13","14","02","03"],"addinfo": "(new)","status":"ko"},
			{"nome": "Gestione servizio","file": "gestione_servizio_new","linkoriginale": "","wdg": ["13","14","02","03"],"addinfo": "(new)","status":"ko"},
			{"nome": "Descrizione servizio","file": "descrizione_servizio_new","linkoriginale": "","wdg": ["13","14","02","03"],"addinfo": "(new)","status":"ko"}
			
		]
	},
	{
		"codice": "investimenti",
		"nome": "Investimenti",
		"wdg": ["15","16","02"],
		"voci": [
			{"nome": "Attivazione trading","file": "attivazione_trading","linkoriginale": "/WEBHT/investimenti/compraVendiTitolo.do?&isin=IT0001233417&codMercatoInfo=MTA&codAreaFinanza=codAreaFinanza","wdg": [],"status":"ok"},
			{"nome": "Situazione","file": "situazione","linkoriginale": "/WEBHT/investimenti/news.do","wdg": [],"strutt":"full","status":"ok"},
			{"nome": "Situazione 2","file": "situazione_2","linkoriginale": "/WEBHT/investimenti/news.do","wdg": [],"status":"ok"},
			{"nome": "Situazione patrimoniale (no professional)","file": "investimenti_non_professional","linkoriginale": "/WEBHT/cc/posizionePatrimoniale.do","wdg": [],"strutt":"full","status":"ok"},
			{"nome": "Situazione patrimoniale","file": "situazione_patrimoniale","linkoriginale": "/WEBHT/cc/posizionePatrimoniale.do","wdg": ["02"],"status":"ok"},
			{"nome": "Titoli preferiti (senza titoli)","file": "titoli_preferiti","linkoriginale": "/WEBHT/investimenti/titoliPreferiti.do","wdg": [],"status":"ok"},
			{"nome": "Titoli preferiti (con titoli)","file": "titoli_preferiti2","linkoriginale": "/WEBHT/investimenti/titoliPreferiti.do","wdg": [],"status":"ok"},
			{"nome": "Dettaglio titolo","file": "dettaglio_titolo","linkoriginale": "/WEBHT/investimenti/dettaglioTitolo.do?&isin=US0231351067&codMercatoInfo=NASDAQ&simbolo=AMZN","wdg": [],"status":"ok"},
			{"nome": "Gestione ordine (Step 1)","file": "gestione_ordini_step1","linkoriginale": "/WEBHT/investimenti/compraVendiTitolo.do?&isin=IT0001233417&codMercatoInfo=MTA&codAreaFinanza=codAreaFinanza","wdg": [],"status":"ok"},
			{"nome": "Gestione ordine (Step 2)","file": "gestione_ordini_step2","linkoriginale": "/WEBHT/investimenti/compraVendiTitolo.do?&isin=IT0001233417&codMercatoInfo=MTA&codAreaFinanza=codAreaFinanza","wdg": [],"status":"ok"},
			{"nome": "Gestione ordine (Step  MIFID)","file": "gestione_ordini_step2_mifid","linkoriginale": "/WEBHT/investimenti/compraVendiTitolo.do?&isin=IT0001233417&codMercatoInfo=MTA&codAreaFinanza=codAreaFinanza","wdg": [],"status":"ok"},
			{"nome": "Gestione ordine (Step 3)","file": "gestione_ordini_step3","linkoriginale": "/WEBHT/investimenti/compraVendiTitolo.do?&isin=IT0001233417&codMercatoInfo=MTA&codAreaFinanza=codAreaFinanza","wdg": [],"status":"ok"},
			{"nome": "Dettaglio ordine","file": "dettaglio_ordine","linkoriginale": "i/WEBHT/investimenti/dettaglioOrdineDossier.do?&isin=IT0001233417&codMercatoInfo=MTA&codAreaFinanza=codAreaFinanza","wdg": [],"status":"ok"},
			{"nome": "Elenco titoli dell'indice","file": "elenco_titoli_indice","linkoriginale": "/WEBHT/investimenti/titoliIndiceForm.do?mercato=MTA&chain=MTA.FTSEMIB&codice=FTSEMIB","wdg": [],"status":"ok"},
			{"nome": "Compravendita","file": "invest_compravendita","linkoriginale": "/WEBHT/investimenti/titoliPreferiti.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Elenco Covered Warrant","file": "elenco_cover_warrant","linkoriginale": "/WEBHT/investimenti/ricercaCWTitolo.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Il tuo portafoglio (non attivo)","file": "il_tuo_portafoglio","linkoriginale": "/WEBHT/investimenti/titoliDossier.do","wdg": [],"status":"ok"},
			{"nome": "Il tuo portafoglio (attivo)","file": "il_tuo_portafoglio_2","linkoriginale": "/WEBHT/investimenti/titoliDossier.do","wdg": [],"status":"ok"},
			{"nome": "Performance","file": "performance","linkoriginale": "WEBHT/investimenti/performanceTitolo.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Ordini e movimenti","file": "ordini_movimenti","linkoriginale": "/WEBHT/investimenti/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Portafoglio simulato","file": "portafoglio_simulato","linkoriginale": "/WEBHT/investimenti/portafoglioSimulato.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (da compilare)","file": "questionario_mifid","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (da compilare - Step 2)","file": "questionario_mifid_step2","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (da compilare - Step 2 - otp)","file": "questionario_mifid_step2_otp","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (da compilare - Step 3 - conferma)","file": "questionario_mifid_step3","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (compilato)","file": "questionario_mifid2","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (compilato - visualizza)","file": "questionario_mifid2_visualizza","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (compilato - modifica)","file": "questionario_mifid2_modifica","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (compilato - modifica - conferma)","file": "questionario_mifid2_modifica_step2","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (step 1 new)","file": "questionario_mifid_step1","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (step 4/2 new)","file": "questionario_mifid_step4.2","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (step 4/3 new)","file": "questionario_mifid_step4.3","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (consolidamento)","file": "questionario_mifid_consolidamento","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Questionario Mifid (stampa)","file": "questionario_mifid_stampa","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "MIFID II (oggetti vari)","file": "questionario_mifid_II","linkoriginale": "/WEBHT/investimenti/mifid.do","wdg": [],"status":"ok"},
			{"nome": "Linea di Trading","file": "linea_trading","linkoriginale": "/WEBHT/investimenti/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Linea di Trading (aderisci)","file": "linea_trading_aderisci","linkoriginale": "/WEBHT/investimenti/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Linea di Trading (aderisci step 2)","file": "linea_trading_aderisci2","linkoriginale": "/WEBHT/investimenti/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Linea di Trading (recedi e cambia)","file": "linea_trading2","linkoriginale": "/WEBHT/investimenti/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Linea di Trading 2 (cambia)","file": "linea_trading2_cambia","linkoriginale": "/WEBHT/investimenti/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Linea di Trading 2 (cambia - Step 2)","file": "linea_trading2_cambia_step2","linkoriginale": "/WEBHT/investimenti/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Linea di Trading 2 (cambia - Step 3 - conferma)","file": "linea_trading2_cambia_step3","linkoriginale": "/WEBHT/investimenti/xxx.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Linea di Trading 2 (recedi)","file": "linea_trading2_recedi","linkoriginale": "/WEBHT/investimenti/xxx.do","wdg": [],"addinfo": "(new)","status":"no"},
			{"nome": "Analisi","file": "analisi","linkoriginale": "/WEBHT/investimenti/xxx.do","wdg": [],"status":"ok"},
			{"nome": "Indici","file": "indici","linkoriginale": "/WEBHT/investimenti/indici.do","wdg": [],"status":"ok"},
			{"nome": "Posizione fiscale","file": "posizione_fiscale","linkoriginale": "/WEBHT/investimenti/posizioneFiscale.do","wdg": [],"status":"ok"},
			{"nome": "Posizione fiscale (ricerca)","file": "posizione_fiscale_ricerca","linkoriginale": "/WEBHT/investimenti/posizioneFiscale.do","wdg": [],"status":"ok"},
			{"nome": "Cambi","file": "cambi","linkoriginale": "/WEBHT/investimenti/cambiForm.do","wdg": [],"status":"ok"},
			{"nome": "Fondi","linkoriginale": "","wdg": [],
				"voci" : [
					{"nome": "Cosa sono i  fondi","file": "cosa_sono_fondi","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Perchè investire","file": "investire","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Fondi Pir","file": "pir","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Pic e Pac","file": "pic_pac","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Ricerca e compravendita fondi","file": "fondi_ricerca_analisi","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Ricerca e analisi (Ricerca)","file": "fondi_ricerca_analisi_ricerca","linkoriginale": "/WEBHT/investimenti/fondiRicercaParametri.do","wdg": [],"addinfo": "(new)", "status":" new"},
					{"nome": "Ricerca e analisi (Ricerca - risultato)","file": "fondi_ricerca_analisi_ricerca_risultato","linkoriginale": "/WEBHT/investimenti/fondiRicercaParametri.do","wdg": [],"addinfo": "(new)", "status":" ok"},
					{"nome": "Ricerca e analisi (Ricerca - sottoscrivi) step 1","file": "fondi_ricerca_analisi_ricerca_sottoscrivi","linkoriginale": "/WEBHT/investimenti/fondiRicercaParametri.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Ricerca e analisi (Ricerca - sottoscrivi) step 2","file": "fondi_ricerca_analisi_ricerca_sottoscrivi_step2","linkoriginale": "/WEBHT/investimenti/fondiRicercaParametri.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Ricerca e analisi (Ricerca - sottoscrivi) step 3","file": "fondi_ricerca_analisi_ricerca_sottoscrivi_step3","linkoriginale": "/WEBHT/investimenti/fondiRicercaParametri.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Ricerca e analisi (Ricerca - sottoscrivi) step 4","file": "fondi_ricerca_analisi_ricerca_sottoscrivi_step4","linkoriginale": "/WEBHT/investimenti/fondiRicercaParametri.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Ricerca e analisi (Ricerca - dettaglio fondo)","file": "fondi_ricerca_analisi_ricerca_dettagliofondo","linkoriginale": "/WEBHT/investimenti/fondiRicercaParametri.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Ricerca e analisi (Ricerca - risultato - Confronto - Ricerca)","file": "fondi_ricerca_analisi_ricerca_risultato_confronto","linkoriginale": "/WEBHT/investimenti/fondiConfrontoFondiInit.do?&fondoInput=42898810","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Ricerca e analisi (Ricerca - risultato - Confronto - Ris. Ric.)","file": "fondi_ricerca_analisi_ricerca_confronto_risultato","linkoriginale": "/WEBHT/investimenti/fondiRicercaParametri.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Ricerca e analisi (Ricerca - risultato - Confronto 2 Fondi)","file": "fondi_ricerca_analisi_ricerca_confronto_fondi","linkoriginale": "/WEBHT/investimenti/fondiRicercaParametri.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Ricerca e analisi (Aletti)","file": "fondi_ricerca_analisi_aletti","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Ricerca e analisi (BlackRock)","file": "fondi_ricerca_analisi_blackrock","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Ricerca e analisi (Schroders)","file": "fondi_ricerca_analisi_schroders","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Ricerca e analisi (Invesco)","file": "fondi_ricerca_analisi_invesco","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Ricerca e analisi (J.P.Morgan)","file": "fondi_ricerca_analisi_jpmorgan","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Ricerca e analisi (Pictet)","file": "fondi_ricerca_analisi_pictet","linkoriginale": "/WEBHT/investimenti/fondiRicerca.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Ordini","file": "fondi_ordini","linkoriginale": "/WEBHT/investimenti/fondiOrdiniElenco.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Fondi preferiti","file": "fondi_preferiti_03","linkoriginale": "/WEBHT/investimenti/fondiPreferitiElenco.do","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Overlayer costi e commissioni","file": "costi_commissioni_overlayer","wdg": [],"addinfo": "(new)","status":" ok"},
					{"nome": "Portafoglio fondi","file": "portafoglio_fondi","linkoriginale": "/WEBHT/investimenti/portafoglioFondi.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Rimborso fondi","file": "rimborso_fondi","linkoriginale": "/WEBHT/investimenti/portafoglioFondi.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Switch fondi (step 1)","file": "switch_fondi","linkoriginale": "/WEBHT/investimenti/portafoglioFondi.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Switch fondi (step 2)","file": "switch_fondi_step2","linkoriginale": "/WEBHT/investimenti/portafoglioFondi.do","wdg": [],"addinfo": "(new)","status":" new"},
					{"nome": "Switch fondi (step 3)","file": "switch_fondi_step3","linkoriginale": "/WEBHT/investimenti/portafoglioFondi.do","wdg": [],"addinfo": "(new)","status":" new"}
				]
			},

			{"nome": "Popup","file": "","linkoriginale": "","wdg": [],
				"voci" : [
			{"linkdiretto": "true", "nome": "Cerca (in Titoli preferiti)","pag": "", "pag_new": "/template/investimenti_situaz_popup_news.php","status":"ok"},
			{"linkdiretto": "true", "nome": "Book 5 livelli (in Titoli preferiti)","pag": "", "pag_new": "/template/popup_investimenti_bookOrdina.php?isin=IT0005218380&codMercatoInfo=MTA","status":"ok"},
			{"linkdiretto": "true", "nome": "Book 5 livelli (in Titoli preferiti - compra)","pag": "", "pag_new": "/template/popup_investimenti_bookOrdina_compra.php","status":"ok"},
			{"linkdiretto": "true", "nome": "Book 5 livelli (in Titoli preferiti - compra step2)","pag": "", "pag_new": "/template/popup_investimenti_bookOrdina_compra2.php","status":"ok"},
			{"linkdiretto": "true", "nome": "Dettaglio titoli (in Dettaglio titoli - Dati quotazione)","pag": "", "pag_new": "/WEBHT/dettaglioTitoloPopup.php","status":"ok"},
			{"linkdiretto": "true", "nome": "Dettaglio titoli (in Dettaglio titoli - Grafico)","pag": "", "pag_new": "/WEBHT/graficoForm.php?isin=US0231351067&codMercatoInfo=NASDAQ&contesto=popUpPage&tipoGrafico=title","status":"ok"},
			{"linkdiretto": "true", "nome": "Dettaglio titoli (in Dettaglio titoli - mercati trattazione)","pag": "", "pag_new": "/WEBHT/mostraMercatiTrattazione.php","status":"ok"},
			{"linkdiretto": "true", "nome": "Dettaglio titoli (in Dettaglio titoli - news odierne)","pag": "", "pag_new": "/template/investimenti/newsHeadlinesForm.php","status":"ok"},
			{"linkdiretto": "true", "nome": "Dettaglio titoli (in Dettaglio titoli - times and sales)","pag": "", "pag_new": "/template/investimenti/TimeAndSalesForm.php?isin=US0231351067&codMercatoInfo=NASDAQ","status":"ok"},
			{"linkdiretto": "true", "nome": "Dettaglio titoli (in Dettaglio titoli - quotazioni storiche)","pag": "", "pag_new": "/template/investimenti/quotazioniStoricheForm.php?isin=US0231351067&codMercatoInfo=NASDAQ","status":"ok"}

				]
			}

		]
	},
	{
		"codice": "servizi",
		"nome": "Servizi per te",
		"wdg": ["02","17","18"],
		"voci": [
			{"nome": "Il tuo profilo","file": "il_tuo_profilo","linkoriginale": "/WEBHT/serviziPerTe/ilTuoProfilo.do","wdg": [],"status":"ok"},
			<?php /*{"nome": "Il tuo profilo 2","file": "il_tuo_profilo2","linkoriginale": "/WEBHT/serviziPerTe/ilTuoProfilo.do","wdg": [],"status":"ok"},*/ ?>
			{"nome": "Il tuo profilo (sostituisci)","file": "il_tuo_profilo_sostituzione","linkoriginale": "/WEBHT/serviziPerTe/ilTuoProfilo.do","wdg": [],"status":"ok"},
			{"nome": "Il tuo profilo (sostituisci - Step 2)","file": "il_tuo_profilo_sostituzione_step2","linkoriginale": "/WEBHT/serviziPerTe/sostituzioneDispositivoSicurezzaCompilazione.do","wdg": [],"status":"ok"},
			{"nome": "Il tuo profilo (sostituisci - Step 3)","file": "il_tuo_profilo_sostituzione_step3","linkoriginale": "/WEBHT/serviziPerTe/sostituzioneDispositivoSicurezzaCompilazione.do","wdg": [],"status":"ok"},
			{"nome": "Il tuo profilo (sostituisci - Step 4)","file": "il_tuo_profilo_sostituzione_step4","linkoriginale": "/WEBHT/serviziPerTe/sostituzioneDispositivoSicurezzaCompilazione.do","wdg": [],"status":"ok"},
			{"nome": "Cambio Pin","file": "cambio_pin","linkoriginale": "/WEBHT/serviziPerTe/cambioPassword.do","wdg": [],"status":"ok"},
			{"nome": "Cambio Pin (Step 2)","file": "cambio_pin_step2","linkoriginale": "/WEBHT/serviziPerTe/cambioPassword.do","wdg": [],"status":"ok"},
			{"nome": "Cambio Pin (Step 3)","file": "cambio_pin_step3","linkoriginale": "/WEBHT/serviziPerTe/cambioPassword.do","wdg": [],"status":"ok"},
			{"nome": "Gestione dispositivi APP","file": "gestione_dispositivi_app","linkoriginale": "/WEBHT/serviziPerTe/gestioneDispositiviApp.do","wdg": [],"status":"ok"},
			{"nome": "Sostituzione Dispositivo Sicurezza Conferma","file": "sostituzione_dispositivo_sicurezza_conferma","linkoriginale": "/WEBHT/serviziPerTe/sostituzioneDispositivoSicurezzaConferma.do","wdg": [],"status":"no"},
			{"nome": "Rapporti in primo piano","file": "rapporti_in_primo_piano","linkoriginale": "/WEBHT/serviziPerTe/rapportiPredefiniti.do","wdg":["02","03","17","18"],"status":"ok"},
			{"nome": "Rapporti in primo piano (modifica c/c)","file": "rapporti_in_primo_piano_modifica01","linkoriginale": "/WEBHT/serviziPerTe/rapportiPredefinitiModifica.do","wdg":["02","03","17","18"],"status":"ok"},
			{"nome": "Rapporti in primo piano (modifica carte)","file": "rapporti_in_primo_piano_modifica02","linkoriginale": "/WEBHT/serviziPerTe/rapportiPredefinitiModifica.do","wdg":["02","03","17","18"],"status":"ok"},
			{"nome": "Rapporti in primo piano (modifica deposito)","file": "rapporti_in_primo_piano_modifica03","linkoriginale": "/WEBHT/serviziPerTe/rapportiPredefinitiModifica.do","wdg":["02","03","17","18"],"status":"ok"},
			{"nome": "Gestione contatti","file": "gestione_contatti","linkoriginale": "/WEBHT/serviziPerTe/contatti.do","wdg": [],"status":"ok"},
			{"nome": "Gestione contatti (inserisci/modifica)","file": "inserisci_modifica_contatto","linkoriginale": "/WEBHT/serviziPerTe/modificaContatto.do","wdg": [],"status":"ok"},
			{"nome": "Il mio calendario","file": "il_mio_calendario","linkoriginale": "/WEBHT/serviziPerTe/ilMioCalendario.do","wdg": [],"status":"ok"},
			{"nome": "Richiedi appuntamento","file": "richiedi_appuntamento","linkoriginale": "/WEBHT/serviziPerTe/richiestaAppuntamentoCompilazione.do","wdg": [],"status":"ok"},
			{"nome": "Richiedi appuntamento (Riepilogo - Step 2)","file": "richiedi_appuntamento_step2","linkoriginale": "/WEBHT/serviziPerTe/richiestaAppuntamentoConferma.do","wdg": [],"status":"ok"},
			{"nome": "Richiedi appuntamento (Esito - Step 3)","file": "richiedi_appuntamento_step3","linkoriginale": "/WEBHT/serviziPerTe/richiestaAppuntamentoEsito.do","wdg": [],"status":"ok"},
			{"nome": "Apri Conto Corrente","file": "apri_conto_corrente","linkoriginale": "/WEBHT/cc/apriCC.do","wdg": [],"addinfo": "(alternativo)","status":"ok"},
			{"nome": "Apri Conto Corrente step 2","file": "apri_conto_corrente_step2","linkoriginale": "/WEBHT/cc/apriCC.do","wdg": [],"addinfo": "(alternativo)","status":"ok"},
			{"nome": "Apri Dossier Titoli","file": "apri_dossier_titoli","linkoriginale": "/WEBHT/investimenti/dossierApri.do","wdg": ["02","10","17","18"],"status":"ok"},
			{"nome": "Apri Dossier Titoli (Intestazioni - Step 2)","file": "dossier_titoli_step2","linkoriginale": "/WEBHT/investimenti/dossierApri.do","wdg": ["02","10","17","18"],"status":"ok"},
			{"nome": "Apri Dossier Titoli (Approfondimento - Step 3)","file": "dossier_titoli_step3","linkoriginale": "/WEBHT/investimenti/dossierAttivazioneApprofondimenti.do","wdg": ["02","10","17","18"],"status":"ok"},
			{"nome": "Apri Dossier Titoli (Riepilogo - Step 4)","file": "dossier_titoli_step4","linkoriginale": "/WEBHT/investimenti/dossierAttivazioneRiepilogo.do","wdg": ["02","10","17","18"],"status":"ok"},
			{"nome": "Apri Dossier Titoli (Contratto - Step 5)","file": "dossier_titoli_step5","linkoriginale": "/WEBHT/investimenti/dossierAttivazioneRiepilogoFDR.do","wdg": ["02","10","17","18"],"status":"ok"},
			{"nome": "Apri Dossier Titoli (Conclusione - Step 6)","file": "dossier_titoli_step6","linkoriginale": "/WEBHT/investimenti/dossierAttivazioneRiepilogoFDR.do","wdg": ["02","10","17","18"],"status":"ok"},
			{"nome": "Apri Conto Deposito","file": "apri_conto_deposito","linkoriginale": "/WEBHT/cd/contoDepositoAttivazione.do","wdg": ["03","10","17","18"],"status":"ok"},
			{"nome": "Richiedi la YouCard","file": "richiedi_youcard","linkoriginale": "/WEBHT/cartaConto/youCardApri.do","wdg": ["02","10","17","18"],"addinfo": "(new)","status":"ok"},
			{"nome": "Richiedi la YouCard (step 1)","file": "richiedi_youcard_step1","linkoriginale": "/WEBHT/cartaConto/youCardApri.do","wdg": ["02","10","17","18"],"addinfo": "(new)","status":"ok"},
			{"nome": "Richiedi la YouCard (step 2)","file": "richiedi_youcard_step2","linkoriginale": "/WEBHT/cartaConto/youCardApri.do","wdg": ["02","10","17","18"],"addinfo": "(new)","status":"ok"},
			{"nome": "Richiedi la YouCard (step 3)","file": "richiedi_youcard_step3","linkoriginale": "/WEBHT/cartaConto/youCardApri.do","wdg": ["02","10","17","18"],"addinfo": "(new)","status":"ok"},
			{"nome": "Richiedi la YouCard (step 4)","file": "richiedi_youcard_step4","linkoriginale": "/WEBHT/cartaConto/youCardApri.do","wdg": ["02","10","17","18"],"addinfo": "(new)","status":"ok"},
			{"nome": "Richiedi la YouCard (step 5)","file": "richiedi_youcard_step5","linkoriginale": "/WEBHT/cartaConto/youCardApri.do","wdg": ["02","10","17","18"],"addinfo": "(new)","status":"ok"},
			{"nome": "News","file": "news","linkoriginale": "/WEBHT/news/elenco.do","wdg": [],"status":"ok"},
			{"nome": "Scarico certificato","file": "scarico_certificato","linkoriginale": "/WEBHT/serviziPerTe/scaricoCertificato.do","wdg": [],"status":"ok"},
			{"nome": "Sicurezza YouWeb","file": "sicurezza_youweb","linkoriginale": "/WEBHT/serviziPerTe/sicurezzaInfo.do","wdg": [],"strutt":"","status":"ok"},
			{"nome": "Contattaci","file": "servizi_contattaci","linkoriginale": "/WEBHT/info/contattaci.do","wdg": [],"status":"ok"},
			{"nome": "Gestione contatti e recapiti","file": "gestione_contatti_recapiti","linkoriginale": "/WEBHT/serviziPerTe/contattiERecapiti.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Gestione email","file": "gestione_email_step1","linkoriginale": "/WEBHT/serviziPerTe/contattiERecapiti/EMail.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Aggiungi/modifica email (modifica - step 2)","file": "gestione_email_step2","linkoriginale": "/WEBHT/serviziPerTe/contattiERecapiti/EMail.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Aggiungi/modifica email (conferma - step 3)","file": "gestione_email_step3","linkoriginale": "/WEBHT/serviziPerTe/contattiERecapiti/EMail.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Aggiungi/modifica email (esito - step 4)","file": "gestione_email_step4","linkoriginale": "/WEBHT/serviziPerTe/contattiERecapiti/EMail.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Gestione cellulare","file": "gestione_cellulare_step1","linkoriginale": "/WEBHT/serviziPerTe/contattiERecapiti/Cellulari.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Aggiungi/modifica cellulare (modifica - step 2)","file": "gestione_cellulare_step2","linkoriginale": "/WEBHT/serviziPerTe/contattiERecapiti/EMail.do","wdg": [],"addinfo": "(new)","status":"ok"},
			{"nome": "Aggiungi/modifica cellulare (conferma - step 3)","file": "gestione_cellulare_step3","linkoriginale": "/WEBHT/serviziPerTe/contattiERecapiti/EMail.do","wdg": [],"addinfo": "(new)","status":"ko"},
			{"nome": "Aggiungi/modifica cellulare (esito - step 4)","file": "gestione_cellulare_step4","linkoriginale": "/WEBHT/serviziPerTe/contattiERecapiti/EMail.do","wdg": [],"addinfo": "(new)","status":"ko"},
			{"nome": "Numeri blocco carte","file": "numeri_blocco_carte","linkoriginale": "","wdg": [],"addinfo": "(new)","status":"ok"}



			<?php /*,
			{"nome": "YouShop","file": "","linkoriginale": "#","wdg": []},
			{"nome": "YouWin","file": "youwin","linkoriginale": "/WEBHT/serviziPerTe/youWin.do","wdg": [] ,"status":"ok"}*/ ?>
		]
	},
	{
		"codice": "linkmenu",
		"nome": "\"Scopri di pi&ugrave;\" nel menu",
		"wdg": ["02"],
		"voci": [

			{"nome": "Conti e depositi","file": "scopri_youapp","linkoriginale": "/WEBHT/news/dettaglio.do?id=737","wdg": [],"status":"ok"},
			{"nome": "Pagamenti","file": "scopri_pagamenti","linkoriginale": "/WEBHT/news/dettaglio.do?id=1198","wdg": ["02","17","18"],"status":"ok"},
			{"nome": "Alert","file": "scopri_alert","linkoriginale": "/WEBHT/news/dettaglio.do?id=1004","wdg": ["02","17","18"],"status":"ok"},
			{"nome": "Posta personale","file": "scopri_postapers","linkoriginale": "/WEBHT/news/dettaglio.do?id=1008","wdg": ["02","17","18"],"status":"ok"},
			{"nome": "Posta investimenti","file": "scopri_investimenti","linkoriginale": "/WEBHT/news/dettaglio.do?id=21","wdg": ["02","17","18"],"status":"ok"},
			{"nome": "Posta personale","file": "scopri_servizixte","linkoriginale": "/WEBHT/news/dettaglio.do?id=1097","wdg": ["02","17","18"],"status":"ok"}

		]
	},
	{
		"codice": "vna",
		"nome": "Voci non alberate",
		"wdg": ["02"],
		"voci": [

			{"nome": "FAQ","file": "faq","linkoriginale": "","wdg": [],"status":"ok"},
			{"nome": "Assistente virtuale","file": "assistente_virtuale","linkoriginale": "","wdg": ["VA","02"],"status":"ok"},
			{"linkdiretto": "true", "nome": "Personalizza Dashboard","pag": "/template/tpl_priv_personalizza_old.php", "pag_new": "/strutt_priv_new.php?pag=personalizza_homepage&wdg=02|17|18","status":"ok"}

		]
	},
	{
		"codice": "strong",
		"nome": "Strong authentication",
		"wdg": ["02"],
		"voci": [
			{"nome": "Strong authentication","file": "strong_autentication","linkoriginale": "","wdg": ["VA","02"],"status":"ok"}
		]
	}
]
