<?php header('content-type: application/json; charset=utf-8'); ?>{
	"mapVector": [
		[
			{"nome":"FTSE", "val":"44.111,00", "perc":"-1,1%", "terna": "MI.EEE.BB0"},
			{"nome":"MIB", "val":"1.111,00", "perc":"0,1%", "terna": "MI.EEE.BB1"},
			{"nome":"DAX 30", "val":"66.111,00", "perc":"-2,1%", "terna": "MI.EEE.BB2"},
			{"nome":"CAC 40", "val":"777.111,00", "perc":"0,1%", "terna": "MI.EEE.BB3"},
			{"nome":"DOW JONES", "val":"2.111,00", "perc":"-2,1%", "terna": "MI.EEE.BB4"},
			{"nome":"NASDAQ 100", "val":"55.111,00", "perc":"3,1%", "terna": "MI.EEE.BB5"},
			{"nome":"NIKKEI", "val":"99.111,00", "perc":"3,1%", "terna": "MI.EEE.BB6"}
		],
		[
			{"nome":"FTSE", "val":"444.222,00", "perc":"1,2%", "terna": "MI.EEE.BB0"},
			{"nome":"MIB", "val":"11.222,00", "perc":"-0,2%", "terna": "MI.EEE.BB1"},
			{"nome":"DAX 30", "val":"666.222,00", "perc":"2,2%", "terna": "MI.EEE.BB2"},
			{"nome":"CAC 40", "val":"77.222,00", "perc":"0,2%", "terna": "MI.EEE.BB3"},
			{"nome":"DOW JONES", "val":"222.222,00", "perc":"-2,2%", "terna": "MI.EEE.BB4"},
			{"nome":"NASDAQ 100", "val":"55.222,00", "perc":"3,2%", "terna": "MI.EEE.BB5"},
			{"nome":"NIKKEI", "val":"9.222,00", "perc":"3,2%", "terna": "MI.EEE.BB6"}
		],
		[
			{"nome":"FTSE", "val":"4.333,00", "perc":"1,3%", "terna": "MI.EEE.BB0"},
			{"nome":"MIB", "val":"111.333,00", "perc":"0,3%", "terna": "MI.EEE.BB1"},
			{"nome":"DAX 30", "val":"666.333,00", "perc":"2,3%", "terna": "MI.EEE.BB2"},
			{"nome":"CAC 40", "val":"777.333,00", "perc":"0,3%", "terna": "MI.EEE.BB3"},
			{"nome":"DOW JONES", "val":"22.333,00", "perc":"2,3%", "terna": "MI.EEE.BB4"},
			{"nome":"NASDAQ 100", "val":"5.333,00", "perc":"-3,3%", "terna": "MI.EEE.BB5"},
			{"nome":"NIKKEI", "val":"99.333,00", "perc":"-3,3%", "terna": "MI.EEE.BB6"}
		],
		[
			{"nome":"FTSE", "val":"44.444,00", "perc":"-1,4%", "terna": "MI.EEE.BB0"},
			{"nome":"MIB", "val":"11.444,00", "perc":"0,4%", "terna": "MI.EEE.BB1"},
			{"nome":"DAX 30", "val":"66.444,00", "perc":"2,4%", "terna": "MI.EEE.BB2"},
			{"nome":"CAC 40", "val":"777.444,00", "perc":"0,4%", "terna": "MI.EEE.BB3"},
			{"nome":"DOW JONES", "val":"22.444,00", "perc":"2,4%", "terna": "MI.EEE.BB4"},
			{"nome":"NASDAQ 100", "val":"55.444,00", "perc":"3,4%", "terna": "MI.EEE.BB5"},
			{"nome":"NIKKEI", "val":"999.444,00", "perc":"3,4%", "terna": "MI.EEE.BB6"}
		],
		[
			{"nome":"FTSE", "val":"444.555,00", "perc":"1,5%", "terna": "MI.EEE.BB0"},
			{"nome":"MIB", "val":"111.555,00", "perc":"-0,5%", "terna": "MI.EEE.BB1"},
			{"nome":"DAX 30", "val":"66.555,00", "perc":"2,5%", "terna": "MI.EEE.BB2"},
			{"nome":"CAC 40", "val":"77.555,00", "perc":"0,5%", "terna": "MI.EEE.BB3"},
			{"nome":"DOW JONES", "val":"222.555,00", "perc":"2,5%", "terna": "MI.EEE.BB4"},
			{"nome":"NASDAQ 100", "val":"5.555,00", "perc":"3,5%", "terna": "MI.EEE.BB5"},
			{"nome":"NIKKEI", "val":"99.555,00", "perc":"-3,5%", "terna": "MI.EEE.BB6"}
		],
		[
			{"nome":"FTSE", "val":"44.666,00", "perc":"1,6%", "terna": "MI.EEE.BB0"},
			{"nome":"MIB", "val":"1.666,00", "perc":"0,6%", "terna": "MI.EEE.BB1"},
			{"nome":"DAX 30", "val":"6.666,00", "perc":"-2,6%", "terna": "MI.EEE.BB2"},
			{"nome":"CAC 40", "val":"777.666,00", "perc":"-0,6%", "terna": "MI.EEE.BB3"},
			{"nome":"DOW JONES", "val":"22.666,00", "perc":"-2,6%", "terna": "MI.EEE.BB4"},
			{"nome":"NASDAQ 100", "val":"5.666,00", "perc":"3,6%", "terna": "MI.EEE.BB5"},
			{"nome":"NIKKEI", "val":"9.666,00", "perc":"3,6%", "terna": "MI.EEE.BB6"}
		]
	],
	"indiciVector": [
		{"nome":"FTSE", "val":"44.666,00", "perc":"1,6%", "terna": "MI.EEE.BB0"},
		{"nome":"MIB", "val":"1.666,00", "perc":"0,6%", "terna": "MI.EEE.BB1"},
		{"nome":"DAX 30", "val":"6.666,00", "perc":"-3,6%", "terna": "MI.EEE.BB2"},
		{"nome":"CAC 40", "val":"777.666,00", "perc":"-0,6%", "terna": "MI.EEE.BB3"},
		{"nome":"DOW JONES", "val":"22.666,00", "perc":"-2,6%", "terna": "MI.EEE.BB4"},
		{"nome":"NASDAQ 100", "val":"5.666,00", "perc":"2,6%", "terna": "MI.EEE.BB5"},
		{"nome":"NIKKEI", "val":"9.666,00", "perc":"3,6%", "terna": "MI.EEE.BB5"}
	],
	"newsVector": [
		{"titolo":"*Fiat0a: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit.","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf0b: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat0c: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf0d: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat0e: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},

		{"titolo":"Edf1a: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat1b: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf1c: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat1d: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf1e: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},

		{"titolo":"*Fiat2a: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf2b: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat2c: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf2d: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat2e: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},

		{"titolo":"Edf3a: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat3b: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf3c: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat3d: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf3e: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},

		{"titolo":"*Fiat4a: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf4b: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat4c: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf4d: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat4e: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},

		{"titolo":"Edf5a: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat5b: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf5c: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat5d: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf5e: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},

		{"titolo":"*Fiat6a: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf6b: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat6c: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf6d: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat6e: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},

		{"titolo":"Edf7a: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat7b: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf7c: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false},
		{"titolo":"*Fiat7d: titolo sospeso, -5,75% teorico. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:47","id":"2787856",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": true},
		{"titolo":"Edf7e: conferma rating A+, outlook stabile. Lorem ipsum dolor sit amet, consectetur adipiscing elit","data":"30\/05\/2012, 16:46","id":"2787853",
			"testo":"bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla bla bla bla bla bla bla<br/> bla bla bla bla bla bla", "skip": false}
	]
}