<?php header('content-type: application/json; charset=utf-8'); ?>{
    "listaRubricaAll": [
        {
            "anagrafica": {
                "alias": "",
                "area": 1,
                "avatar_file": "",
                "banca": 19,
                "cap": "75008",
                "civico": "",
                "codice_fiscale_p_iva": "",
                "cognome_rag_soc": "Paroni",
                "comune": "Paris",
                "comune_nascita": "",
                "contatto_veloce": false,
                "data_nascita": null,
                "email": "rocco@tano.it",
                "flg_carta": 0,
                "flg_estero": 0,
                "flg_poste": 0,
                "flg_rapporto": 2,
                "flg_telefono": 1,
                "flg_tv": 0,
                "id": 8876805,
                "id_utente": "0001088",
                "indirizzo": "109 Avenue des Champs Élysées",
                "iniziale": "\u0000",
                "nazione": "FR",
                "nazione_nascita": "",
                "nome": "Alberto",
                "prov_nascita": "",
                "provincia": "AG",
                "referente": "",
                "sesso": "\u0000",
                "tipologia": 1,
                "tms_modifica": {
                    "date": 1,
                    "day": 2,
                    "hours": 14,
                    "minutes": 27,
                    "month": 6,
                    "nanos": 0,
                    "seconds": 8,
                    "time": 1404217628000,
                    "timezoneOffset": -120,
                    "year": 114
                }
            },
            "avatar": null,
            "carta": [],
            "id": null,
            "rapporto": [],
            "telefono": [],
            "tv": []
        },
        {
            "anagrafica": {
                "alias": "",
                "area": 1,
                "avatar_file": "",
                "banca": 19,
                "cap": "26013",
                "civico": "",
                "codice_fiscale_p_iva": "",
                "cognome_rag_soc": "arraff",
                "comune": "",
                "comune_nascita": "",
                "contatto_veloce": false,
                "data_nascita": null,
                "email": "raffaele.iori@tiscali.it",
                "flg_carta": 0,
                "flg_estero": 0,
                "flg_poste": 0,
                "flg_rapporto": 2,
                "flg_telefono": 0,
                "flg_tv": 0,
                "id": 8876753,
                "id_utente": "0001088",
                "indirizzo": "Via Mulini, 5",
                "iniziale": "A",
                "nazione": "IT",
                "nazione_nascita": "",
                "nome": "",
                "prov_nascita": "",
                "provincia": "AG",
                "referente": "",
                "sesso": "\u0000",
                "tipologia": 1,
                "tms_modifica": {
                    "date": 18,
                    "day": 2,
                    "hours": 14,
                    "minutes": 51,
                    "month": 2,
                    "nanos": 0,
                    "seconds": 16,
                    "time": 1395150676000,
                    "timezoneOffset": -60,
                    "year": 114
                }
            },
            "avatar": null,
            "carta": [],
            "id": null,
            "rapporto": [],
            "telefono": [],
            "tv": []
        },
        {
            "anagrafica": {
                "alias": "",
                "area": 1,
                "avatar_file": "",
                "banca": 19,
                "cap": "",
                "civico": "",
                "codice_fiscale_p_iva": "",
                "cognome_rag_soc": "Mario Pace",
                "comune": "",
                "comune_nascita": "",
                "contatto_veloce": false,
                "data_nascita": null,
                "email": "mario.pace@gmail.com",
                "flg_carta": 0,
                "flg_estero": 0,
                "flg_poste": 0,
                "flg_rapporto": 0,
                "flg_telefono": 1,
                "flg_tv": 0,
                "id": 8876862,
                "id_utente": "0001088",
                "indirizzo": "",
                "iniziale": "M",
                "nazione": "",
                "nazione_nascita": "",
                "nome": "",
                "prov_nascita": "",
                "provincia": "  ",
                "referente": "",
                "sesso": "\u0000",
                "tipologia": 1,
                "tms_modifica": {
                    "date": 4,
                    "day": 2,
                    "hours": 11,
                    "minutes": 46,
                    "month": 5,
                    "nanos": 0,
                    "seconds": 34,
                    "time": 1370339194000,
                    "timezoneOffset": -120,
                    "year": 113
                }
            },
            "avatar": null,
            "carta": [],
            "id": null,
            "rapporto": [],
            "telefono": [],
            "tv": []
        },
        {
            "anagrafica": {
                "alias": "",
                "area": 1,
                "avatar_file": "",
                "banca": 19,
                "cap": "",
                "civico": "",
                "codice_fiscale_p_iva": "",
                "cognome_rag_soc": "zz mug",
                "comune": "",
                "comune_nascita": "",
                "contatto_veloce": true,
                "data_nascita": null,
                "email": "ant@ant.it",
                "flg_carta": 0,
                "flg_estero": 0,
                "flg_poste": 0,
                "flg_rapporto": 3,
                "flg_telefono": 0,
                "flg_tv": 0,
                "id": 8877091,
                "id_utente": "0001088",
                "indirizzo": "",
                "iniziale": "Z",
                "nazione": "IT",
                "nazione_nascita": "",
                "nome": "",
                "prov_nascita": "",
                "provincia": "  ",
                "referente": "",
                "sesso": "\u0000",
                "tipologia": 1,
                "tms_modifica": {
                    "date": 17,
                    "day": 3,
                    "hours": 17,
                    "minutes": 3,
                    "month": 6,
                    "nanos": 0,
                    "seconds": 13,
                    "time": 1374073393000,
                    "timezoneOffset": -120,
                    "year": 113
                }
            },
            "avatar": null,
            "carta": [],
            "id": null,
            "rapporto": [],
            "telefono": [],
            "tv": []
        }
    ],
    "esito": "ok"
}