<?php header('content-type: application/json; charset=utf-8'); ?>{
  "esito":"ok",
  "esitiRicerca":[
    {
      "data":"20/06/17&#160;",
      "desc":"INTER  5359589101474452 RIF. 00023906436&#160;",
      "idtipo":"RPR",
      "tipo":"Ricariche prepagate",
      "stato":"Eseguito&#160;",
      "importo":"315,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":false,
      "param":"&numeroCRO=21906436&tipoDisposizione=RPR",
      "data-key":"20170620000000",
      "dettaglio":"&#160;",
      "copia":"&#160;",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"08/06/17&#160;",
      "desc":"Marina Peroni&#160;",
      "idtipo":"SEP",
      "tipo":"Bonifici",
      "stato":"Eseguito&#160;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=21831106&tipoDisposizione=SEP",
      "importo":"300,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":true,
      "param":"&numeroCRO=21831106&tipoDisposizione=SEP",
      "data-key":"20170608000000",
      "dettaglio":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/2l/action/banking/WsBonificoSepaDetail.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_bonifico_ordinario&OBSKEY3=nav_priv_wbx_bonifico_ordinario&clean=true&numeroCRO=21831106&tipoDisposizione=SEP'><i class='icon-2x icon icon-zoom_piu_filled'><\/i><\/a><\/a>",
      "copia":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/2l/action/banking/WsBonificoSepaCopia.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_bonifico_ordinario&OBSKEY3=nav_priv_wbx_bonifico_ordinario&numeroCRO=21831106&tipoDisposizione=SEP&verificaPagamento=1'><i class='icon icon-2x icon-documenti'><\/i><\/a>",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"29/05/17&#160;",
      "desc":"Marina Peroni&#160;",
      "idtipo":"SEP",
      "tipo":"Bonifici",
      "stato":"Eseguito&#160;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=21760365&tipoDisposizione=SEP",
      "importo":"155,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":true,
      "param":"&numeroCRO=21760365&tipoDisposizione=SEP",
      "data-key":"20170529000000",
      "dettaglio":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/2l/action/banking/WsBonificoSepaDetail.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_bonifico_ordinario&OBSKEY3=nav_priv_wbx_bonifico_ordinario&clean=true&numeroCRO=21760365&tipoDisposizione=SEP'><i class='icon-2x icon icon-zoom_piu_filled'><\/i><\/a><\/a>",
      "copia":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/2l/action/banking/WsBonificoSepaCopia.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_bonifico_ordinario&OBSKEY3=nav_priv_wbx_bonifico_ordinario&numeroCRO=21760365&tipoDisposizione=SEP&verificaPagamento=1'><i class='icon icon-2x icon-documenti'><\/i><\/a>",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"15/05/17&#160;",
      "desc":"366 /3055481&#160;",
      "idtipo":"CEL",
      "tipo":"Ricariche cellulari/TV",
      "stato":"Eseguito&#160;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=21669669&tipoDisposizione=CEL",
      "importo":"15,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":false,
      "param":"&numeroCRO=21669669&tipoDisposizione=CEL",
      "data-key":"20170515000000",
      "dettaglio":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/3l/action/banking/WsCellRechargeActionDetail.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_ricaric_cell&OBSKEY3=nav_priv_wbx_ricarica&numeroCRO=21669669&tipoDisposizione=CEL'><i class='icon-2x icon icon-zoom_piu_filled'><\/i><\/a><\/a>",
      "copia":"&#160;",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"15/05/17",
      "desc":"ROSSI             ANDREA",
      "idtipo":"F24",
      "tipo":"Delega F24",
      "stato":"Eseguito",
      "importo":"1.817,47 &euro;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?chiaveDelega=20170515140844<BHC&tipoDisposizione=F24&numeroCRO=0&stato=Eseguito",
      "data-key":20170515000000,
      "annullabile":false,
      "copiabile":true,
      "param":"&hdChiave=20170515140844<BHC&hdStato=I&tipoDisposizione=F24",
      "dettaglio":"<a class='no-underline btn-icon' href='javascript:vaiDettaglioF24(\"20170515140844<BHC\",\"I\");'><i class='icon-2x icon icon-zoom_piu_filled'><\/i><\/a><\/a>",
      "copia":"<a class='no-underline btn-icon' href='javascript:vaiCopiaF24(\"20170515140844<BHC\");'><i class='icon icon-2x icon-documenti'><\/i><\/a>",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"11/05/17&#160;",
      "desc":"INTER  5359589101474452 RIF. 00023647622&#160;",
      "idtipo":"RPR",
      "tipo":"Ricariche prepagate",
      "stato":"Eseguito&#160;",
      "importo":"150,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":false,
      "param":"&numeroCRO=21647622&tipoDisposizione=RPR",
      "data-key":"20170511000000",
      "dettaglio":"&#160;",
      "copia":"&#160;",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"11/05/17",
      "desc":"ROSSI             ANDREA",
      "idtipo":"F24",
      "tipo":"Delega F24",
      "stato":"Eseguito",
      "importo":"82,00 &euro;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?chiaveDelega=20170511162258<BHC&tipoDisposizione=F24&numeroCRO=0&stato=Eseguito",
      "data-key":20170511000000,
      "annullabile":false,
      "copiabile":true,
      "param":"&hdChiave=20170511162258<BHC&hdStato=I&tipoDisposizione=F24",
      "dettaglio":"<a class='no-underline btn-icon' href='javascript:vaiDettaglioF24(\"20170511162258<BHC\",\"I\");'><i class='icon-2x icon icon-zoom_piu_filled'><\/i><\/a><\/a>",
      "copia":"<a class='no-underline btn-icon' href='javascript:vaiCopiaF24(\"20170511162258<BHC\");'><i class='icon icon-2x icon-documenti'><\/i><\/a>",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"08/05/17&#160;",
      "desc":"Federico Pozzi&#160;",
      "idtipo":"SEP",
      "tipo":"Bonifici",
      "stato":"Eseguito&#160;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=21624176&tipoDisposizione=SEP",
      "importo":"183,60 &euro;&#160;",
      "annullabile":false,
      "copiabile":true,
      "param":"&numeroCRO=21624176&tipoDisposizione=SEP",
      "data-key":"20170508000000",
      "dettaglio":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/2l/action/banking/WsBonificoSepaDetail.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_bonifico_ordinario&OBSKEY3=nav_priv_wbx_bonifico_ordinario&clean=true&numeroCRO=21624176&tipoDisposizione=SEP'><i class='icon-2x icon icon-zoom_piu_filled'><\/i><\/a><\/a>",
      "copia":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/2l/action/banking/WsBonificoSepaCopia.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_bonifico_ordinario&OBSKEY3=nav_priv_wbx_bonifico_ordinario&numeroCRO=21624176&tipoDisposizione=SEP&verificaPagamento=1'><i class='icon icon-2x icon-documenti'><\/i><\/a>",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"08/05/17&#160;",
      "desc":"Federico Pozzi&#160;",
      "idtipo":"SEP",
      "tipo":"Bonifici",
      "stato":"Eseguito&#160;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=21624195&tipoDisposizione=SEP",
      "importo":"234,60 &euro;&#160;",
      "annullabile":false,
      "copiabile":true,
      "param":"&numeroCRO=21624195&tipoDisposizione=SEP",
      "data-key":"20170508000000",
      "dettaglio":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/2l/action/banking/WsBonificoSepaDetail.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_bonifico_ordinario&OBSKEY3=nav_priv_wbx_bonifico_ordinario&clean=true&numeroCRO=21624195&tipoDisposizione=SEP'><i class='icon-2x icon icon-zoom_piu_filled'><\/i><\/a><\/a>",
      "copia":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/2l/action/banking/WsBonificoSepaCopia.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_bonifico_ordinario&OBSKEY3=nav_priv_wbx_bonifico_ordinario&numeroCRO=21624195&tipoDisposizione=SEP&verificaPagamento=1'><i class='icon icon-2x icon-documenti'><\/i><\/a>",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"06/05/17&#160;",
      "desc":"366 /3055481&#160;",
      "idtipo":"CEL",
      "tipo":"Ricariche cellulari/TV",
      "stato":"Eseguito&#160;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=21610631&tipoDisposizione=CEL",
      "importo":"15,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":false,
      "param":"&numeroCRO=21610631&tipoDisposizione=CEL",
      "data-key":"20170506000000",
      "dettaglio":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/3l/action/banking/WsCellRechargeActionDetail.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_ricaric_cell&OBSKEY3=nav_priv_wbx_ricarica&numeroCRO=21610631&tipoDisposizione=CEL'><i class='icon-2x icon icon-zoom_piu_filled'><\/i><\/a><\/a>",
      "copia":"&#160;",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"19/04/17&#160;",
      "desc":"INTER  5359589101474452 RIF. 00023498463&#160;",
      "idtipo":"RCJ",
      "tipo":"Rimborsi prepagate",
      "stato":"Eseguito&#160;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=21498463&tipoDisposizione=RCJ",
      "importo":"100,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":false,
      "param":"&numeroCRO=21498463&tipoDisposizione=RCJ",
      "data-key":"20170419000000",
      "dettaglio":"&#160;",
      "copia":"&#160;",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"17/04/17&#160;",
      "desc":"366 /3055481&#160;",
      "idtipo":"CEL",
      "tipo":"Ricariche cellulari/TV",
      "stato":"Eseguito&#160;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=21485995&tipoDisposizione=CEL",
      "importo":"15,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":false,
      "param":"&numeroCRO=21485995&tipoDisposizione=CEL",
      "data-key":"20170417000000",
      "dettaglio":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/3l/action/banking/WsCellRechargeActionDetail.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_ricaric_cell&OBSKEY3=nav_priv_wbx_ricarica&numeroCRO=21485995&tipoDisposizione=CEL'><i class='icon-2x icon icon-zoom_piu_filled'><\/i><\/a><\/a>",
      "copia":"&#160;",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"17/04/17&#160;",
      "desc":"366 /3055481&#160;",
      "idtipo":"CEL",
      "tipo":"Ricariche cellulari/TV",
      "stato":"Eseguito&#160;",
      "info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=21485867&tipoDisposizione=CEL",
      "importo":"15,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":false,
      "param":"&numeroCRO=21485867&tipoDisposizione=CEL",
      "data-key":"20170417000000",
      "dettaglio":"<a class='no-underline btn-icon' href='/webankpri/wbOnetoone/3l/action/banking/WsCellRechargeActionDetail.action?OBSCNT=TAB&tabId=nav_priv_wbx_sportello&OBSKEY=nav_priv_wbx_ricaric_cell&OBSKEY3=nav_priv_wbx_ricarica&numeroCRO=21485867&tipoDisposizione=CEL'><i class='icon-2x icon icon-zoom_piu_filled'><\/i><\/a><\/a>",
      "copia":"&#160;",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"13/04/17&#160;",
      "desc":"INTER  5359589101474452 RIF. 00023464954&#160;",
      "idtipo":"RPR",
      "tipo":"Ricariche prepagate",
      "stato":"Eseguito&#160;",
      "importo":"100,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":false,
      "param":"&numeroCRO=21464954&tipoDisposizione=RPR",
      "data-key":"20170413000000",
      "dettaglio":"&#160;",
      "copia":"&#160;",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    },
    {
      "data":"12/04/17&#160;",
      "desc":"INTER  5359589101474452 RIF. 00023463619&#160;",
      "idtipo":"RPR",
      "tipo":"Ricariche prepagate",
      "stato":"Eseguito&#160;",
      "importo":"150,00 &euro;&#160;",
      "annullabile":false,
      "copiabile":false,
      "param":"&numeroCRO=21463619&tipoDisposizione=RPR",
      "data-key":"20170412000000",
      "dettaglio":"&#160;",
      "copia":"&#160;",
      "annulla":"<i class='icon icon-2x icon-alert_error_fill disabled'><\/i>"
    }
  ]
}