<!-- BOTTONE COLOR VERDE PIENO OVER BIANCO-->
	<a class="btn-grlit btn-hover-white">LOREM IPSUM</a>
<!-- FINE BOTTONE COLOR VERDE PIENO  OVER BIANCO -->
<!--SE &egrave; UN SUBMIT DI FORM- USARE BUTTON TYPE="SUBMIT"->
<!--SE SI VUOLE FONT_SIZE 14 AGGIUNGERE CLASSE btn-fs14 -->
<!--SE SI VUOLE FONT_SIZE 24 AGGIUNGERE CLASSE btn-fs24 -->
