<!-- BOTTONE  BIANCO OVER NERO-->
	<!--AGGIUNGERE TYPE="SUBMIT SE &egrave; UN SUBMIT DI FORM-->
	<a class="btn-whlit btn-arrow">LOREM IPSUM</a>
<!-- FINE BOTTONE BIANCO OVER NERO--->
<!--SE &egrave; UN SUBMIT DI FORM- USARE BUTTON TYPE="SUBMIT"->
<!--SE SI VUOLE FONT_SIZE 14 AGGIUNGERE CLASSE btn-fs14 -->
<!--SE SI VUOLE FONT_SIZE 24 AGGIUNGERE CLASSE btn-fs24 -->
