export const residenzeValues = [
    { value: "", text: "" },
    { value: "238|ABU DHABI|X", text: "ABU DHABI" },
    { value: "2|AFGHANISTAN|X", text: "AFGHANISTAN" },
    { value: "206|AFRICA DEL SUD OVEST - NAMIBIA|X", text: "AFRICA DEL SUD OVEST - NAMIBIA" },
    { value: "246|AFRICA SPAGNOLA|S", text: "AFRICA SPAGNOLA" },
    { value: "239|AJMAN|X", text: "AJMAN" },
    { value: "292|ALAND ISOLE|X", text: "ALAND ISOLE" },
    { value: "87|ALBANIA|X", text: "ALBANIA" },
    { value: "3|ALGERIA|X", text: "ALGERIA" },
    { value: "148|AMERICAN SAMOA|X", text: "AMERICAN SAMOA" },
    { value: "4|ANDORRA|S", text: "ANDORRA" },
    { value: "133|ANGOLA|X", text: "ANGOLA" },
    { value: "209|ANGUILLA|X", text: "ANGUILLA" },
    { value: "197|ANTIGUA E BARBUDA|X", text: "ANTIGUA E BARBUDA" },
    { value: "5|ARABIA SAUDITA|S", text: "ARABIA SAUDITA" },
    { value: "6|ARGENTINA|S", text: "ARGENTINA" },
    { value: "266|ARMENIA|X", text: "ARMENIA" },
    { value: "212|ARUBA|X", text: "ARUBA" },
    { value: "227|ASCENSION|S", text: "ASCENSION" },
    { value: "7|AUSTRALIA|S", text: "AUSTRALIA" },
    { value: "8|AUSTRIA|S", text: "AUSTRIA" },
    { value: "268|AZERBAIGIAN|X", text: "AZERBAIGIAN" },
    { value: "234|AZZORRE ISOLE|S", text: "AZZORRE ISOLE" },
    { value: "160|BAHAMA|X", text: "BAHAMA" },
    { value: "169|BAHREIN|X", text: "BAHREIN" },
    { value: "130|BANGLADESH|X", text: "BANGLADESH" },
    { value: "118|BARBADOS|X", text: "BARBADOS" },
    { value: "9|BELGIO|S", text: "BELGIO" },
    { value: "198|BELIZE|S", text: "BELIZE" },
    { value: "158|BENIN|X", text: "BENIN" },
    { value: "207|BERMUDA|N", text: "BERMUDA" },
    { value: "97|BHUTAN|X", text: "BHUTAN" },
    { value: "264|BIELORUSSIA|X", text: "BIELORUSSIA" },
    { value: "10|BOLIVIA|X", text: "BOLIVIA" },
    { value: "295|BONAIRE SAINT EUSTATIUS AND SABA|X", text: "BONAIRE SAINT EUSTATIUS AND SABA" },
    { value: "274|BOSNIA ERZEGOVINA|X", text: "BOSNIA ERZEGOVINA" },
    { value: "98|BOTSWANA|X", text: "BOTSWANA" },
    { value: "11|BRASILE|S", text: "BRASILE" },
    { value: "125|BRUNEI DARUSSALAM|X", text: "BRUNEI DARUSSALAM" },
    { value: "12|BULGARIA|S", text: "BULGARIA" },
    { value: "142|BURKINA FASO|X", text: "BURKINA FASO" },
    { value: "25|BURUNDI|X", text: "BURUNDI" },
    { value: "135|CAMBOGIA (CAMPUCEA)|X", text: "CAMBOGIA (CAMPUCEA)" },
    { value: "119|CAMERUN|X", text: "CAMERUN" },
    { value: "139|CAMPIONE D'ITALIA|S", text: "CAMPIONE D'ITALIA" },
    { value: "13|CANADA|S", text: "CANADA" },
    { value: "211|CAYMAN ISOLE|N", text: "CAYMAN ISOLE" },
    { value: "230|CHAFARINAS|S", text: "CHAFARINAS" },
    { value: "144|CIAD|X", text: "CIAD" },
    { value: "15|CILE|X", text: "CILE" },
    { value: "101|CIPRO|S", text: "CIPRO" },
    { value: "93|CITTÀ DEL VATICANO|X", text: "CITTÀ DEL VATICANO" },
    { value: "223|CLIPPERTON|S", text: "CLIPPERTON" },
    { value: "17|COLOMBIA|S", text: "COLOMBIA" },
    { value: "176|COMORE|X", text: "COMORE" },
    { value: "18|CONGO REPUBBLICA DEMOCRATICA|X", text: "CONGO REPUBBLICA DEMOCRATICA" },
    { value: "145|CONGO REPUBBLICA POPOLARE|X", text: "CONGO REPUBBLICA POPOLARE" },
    { value: "74|COREA DEL NORD|X", text: "COREA DEL NORD" },
    { value: "84|COREA DEL SUD|S", text: "COREA DEL SUD" },
    { value: "146|COSTA D'AVORIO|X", text: "COSTA D'AVORIO" },
    { value: "19|COSTARICA|S", text: "COSTARICA" },
    { value: "261|CROAZIA|S", text: "CROAZIA" },
    { value: "20|CUBA|X", text: "CUBA" },
    { value: "296|CURACAO|X", text: "CURACAO" },
    { value: "21|DANIMARCA|S", text: "DANIMARCA" },
    { value: "192|DOMINICA|X", text: "DOMINICA" },
    { value: "240|DUBAI|X", text: "DUBAI" },
    { value: "24|ECUADOR|X", text: "ECUADOR" },
    { value: "23|EGITTO|X", text: "EGITTO" },
    { value: "64|EL SALVADOR|X", text: "EL SALVADOR" },
    { value: "277|ERITREA|X", text: "ERITREA" },
    { value: "257|ESTONIA|S", text: "ESTONIA" },
    { value: "26|ETIOPIA|X", text: "ETIOPIA" },
    { value: "190|FALKLAND|X", text: "FALKLAND" },
    { value: "27|FILIPPINE|X", text: "FILIPPINE" },
    { value: "28|FINLANDIA|S", text: "FINLANDIA" },
    { value: "29|FRANCIA|S", text: "FRANCIA" },
    { value: "241|FUIJAYRAH|X", text: "FUIJAYRAH" },
    { value: "157|GABON|X", text: "GABON" },
    { value: "164|GAMBIA|X", text: "GAMBIA" },
    { value: "267|GEORGIA|X", text: "GEORGIA" },
    { value: "112|GHANA|X", text: "GHANA" },
    { value: "82|GIAMAICA|X", text: "GIAMAICA" },
    { value: "88|GIAPPONE|S", text: "GIAPPONE" },
    { value: "102|GIBILTERRA|S", text: "GIBILTERRA" },
    { value: "113|GIBUTI|X", text: "GIBUTI" },
    { value: "122|GIORDANIA|X", text: "GIORDANIA" },
    { value: "228|GOUGH|S", text: "GOUGH" },
    { value: "32|GRECIA|S", text: "GRECIA" },
    { value: "156|GRENADA|X", text: "GRENADA" },
    { value: "200|GROENLANDIA|S", text: "GROENLANDIA" },
    { value: "214|GUADALUPA|X", text: "GUADALUPA" },
    { value: "154|GUAM|X", text: "GUAM" },
    { value: "33|GUATEMALA|X", text: "GUATEMALA" },
    { value: "123|GUAYANA FRANCESE|X", text: "GUAYANA FRANCESE" },
    { value: "201|GUERNSEY C.I.|S", text: "GUERNSEY C.I." },
    { value: "137|GUINEA|X", text: "GUINEA" },
    { value: "185|GUINEA BISSAU|X", text: "GUINEA BISSAU" },
    { value: "167|GUINEA EQUATORIALE|X", text: "GUINEA EQUATORIALE" },
    { value: "159|GUYANA|X", text: "GUYANA" },
    { value: "34|HAITI|X", text: "HAITI" },
    { value: "284|HEARD E MCDONALD ISOLE|X", text: "HEARD E MCDONALD ISOLE" },
    { value: "35|HONDURAS|X", text: "HONDURAS" },
    { value: "103|HONG KONG|S", text: "HONG KONG" },
    { value: "114|INDIA|S", text: "INDIA" },
    { value: "129|INDONESIA|X", text: "INDONESIA" },
    { value: "39|IRAN|X", text: "IRAN" },
    { value: "38|IRAQ|X", text: "IRAQ" },
    { value: "40|IRLANDA|S", text: "IRLANDA" },
    { value: "41|ISLANDA|S", text: "ISLANDA" },
    { value: "203|ISOLA DI MAN|S", text: "ISOLA DI MAN" },
    { value: "100|ISOLE CANARIE|S", text: "ISOLE CANARIE" },
    { value: "256|ISOLE CAROLINE|S", text: "ISOLE CAROLINE" },
    { value: "255|ISOLE CHAGOS|S", text: "ISOLE CHAGOS" },
    { value: "237|ISOLE COOK|X", text: "ISOLE COOK" },
    { value: "188|ISOLE DEL CAPO VERDE|X", text: "ISOLE DEL CAPO VERDE" },
    { value: "204|ISOLE FAEROER|S", text: "ISOLE FAEROER" },
    { value: "161|ISOLE FIGI|X", text: "ISOLE FIGI" },
    { value: "217|ISOLE MARSHALL|S", text: "ISOLE MARSHALL" },
    { value: "249|ISOLE VERGINI BRITANNICHE|X", text: "ISOLE VERGINI BRITANNICHE" },
    { value: "178|ISOLE WAKE|S", text: "ISOLE WAKE" },
    { value: "182|ISRAELE|S", text: "ISRAELE" },
    { value: "202|JERSEY|S", text: "JERSEY" },
    { value: "269|KAZAKISTAN|X", text: "KAZAKISTAN" },
    { value: "116|KENYA|X", text: "KENYA" },
    { value: "270|KIRGHIZISTAN|X", text: "KIRGHIZISTAN" },
    { value: "194|KIRIBATI|X", text: "KIRIBATI" },
    { value: "126|KUWAIT|S", text: "KUWAIT" },
    { value: "136|LAOS|X", text: "LAOS" },
    { value: "89|LESOTHO|X", text: "LESOTHO" },
    { value: "258|LETTONIA|S", text: "LETTONIA" },
    { value: "95|LIBANO|X", text: "LIBANO" },
    { value: "44|LIBERIA|X", text: "LIBERIA" },
    { value: "45|LIBIA|X", text: "LIBIA" },
    { value: "90|LIECHTENSTEIN|S", text: "LIECHTENSTEIN" },
    { value: "259|LITUANIA|S", text: "LITUANIA" },
    { value: "92|LUSSEMBURGO|S", text: "LUSSEMBURGO" },
    { value: "59|MACAO|N", text: "MACAO" },
    { value: "278|MACEDONIA|X", text: "MACEDONIA" },
    { value: "104|MADAGASCAR|X", text: "MADAGASCAR" },
    { value: "235|MADEIRA|S", text: "MADEIRA" },
    { value: "56|MALAWI|X", text: "MALAWI" },
    { value: "106|MALAYSIA|S", text: "MALAYSIA" },
    { value: "127|MALDIVE|X", text: "MALDIVE" },
    { value: "149|MALI|X", text: "MALI" },
    { value: "105|MALTA|S", text: "MALTA" },
    { value: "219|MARIANNE (ISOLE)|X", text: "MARIANNE (ISOLE)" },
    { value: "107|MAROCCO|X", text: "MAROCCO" },
    { value: "213|MARTINICA|X", text: "MARTINICA" },
    { value: "141|MAURITANIA|X", text: "MAURITANIA" },
    { value: "128|MAURIZIO|X", text: "MAURIZIO" },
    { value: "226|MAYOTTE|X", text: "MAYOTTE" },
    { value: "231|MELILLA|S", text: "MELILLA" },
    { value: "46|MESSICO|S", text: "MESSICO" },
    { value: "215|MICRONESIA|X", text: "MICRONESIA" },
    { value: "177|MIDWAY ISOLE|S", text: "MIDWAY ISOLE" },
    { value: "265|MOLDAVIA|X", text: "MOLDAVIA" },
    { value: "91|MONACO|X", text: "MONACO" },
    { value: "110|MONGOLIA|X", text: "MONGOLIA" },
    { value: "290|MONTENEGRO|X", text: "MONTENEGRO" },
    { value: "208|MONTSERRAT|N", text: "MONTSERRAT" },
    { value: "134|MOZAMBICO|X", text: "MOZAMBICO" },
    { value: "83|MYANMAR|X", text: "MYANMAR" },
    { value: "109|NAURU|S", text: "NAURU" },
    { value: "115|NEPAL|X", text: "NEPAL" },
    { value: "47|NICARAGUA|X", text: "NICARAGUA" },
    { value: "150|NIGER|X", text: "NIGER" },
    { value: "117|NIGERIA|X", text: "NIGERIA" },
    { value: "205|NIUE - SAVAGE|X", text: "NIUE - SAVAGE" },
    { value: "285|NORFOLK ISOLE|X", text: "NORFOLK ISOLE" },
    { value: "48|NORVEGIA|S", text: "NORVEGIA" },
    { value: "253|NUOVA CALEDONIA|X", text: "NUOVA CALEDONIA" },
    { value: "49|NUOVA ZELANDA|S", text: "NUOVA ZELANDA" },
    { value: "175|OCEANIA BRITANNICA|X", text: "OCEANIA BRITANNICA" },
    { value: "252|OCEANIA DEGLI STATI UNITI|X", text: "OCEANIA DEGLI STATI UNITI" },
    { value: "163|OMAN|X", text: "OMAN" },
    { value: "50|PAESI BASSI O OLANDA|S", text: "PAESI BASSI O OLANDA" },
    { value: "36|PAKISTAN|X", text: "PAKISTAN" },
    { value: "279|PALESTINA, TERRITORI AUTONOMI|X", text: "PALESTINA, TERRITORI AUTONOMI" },
    { value: "51|PANAMA|X", text: "PANAMA" },
    { value: "186|PAPUA E NUOVA GUINEA|X", text: "PAPUA E NUOVA GUINEA" },
    { value: "52|PARAGUAY|X", text: "PARAGUAY" },
    { value: "232|PENON DE ALHUCEMAS|S", text: "PENON DE ALHUCEMAS" },
    { value: "233|PENON DE VELEZ DE LA GOMERA|S", text: "PENON DE VELEZ DE LA GOMERA" },
    { value: "53|PERU'|X", text: "PERU'" },
    { value: "225|POLINESIA FRANCESE|X", text: "POLINESIA FRANCESE" },
    { value: "54|POLONIA|S", text: "POLONIA" },
    { value: "55|PORTOGALLO|S", text: "PORTOGALLO" },
    { value: "220|PORTORICO|X", text: "PORTORICO" },
    { value: "168|QATAR|X", text: "QATAR" },
    { value: "242|RAS EL KHAIMAN|X", text: "RAS EL KHAIMAN" },
    { value: "31|REGNO UNITO|S", text: "REGNO UNITO" },
    { value: "22|REP. CINA NAZ. (TAIWAN)|X", text: "REP. CINA NAZ. (TAIWAN)" },
    { value: "275|REPUBBLICA CECA|S", text: "REPUBBLICA CECA" },
    { value: "143|REPUBBLICA CENTRAFRICANA|X", text: "REPUBBLICA CENTRAFRICANA" },
    { value: "291|REPUBBLICA DEL KOSOVO|X", text: "REPUBBLICA DEL KOSOVO" },
    { value: "216|REPUBBLICA DI PALAU|X", text: "REPUBBLICA DI PALAU" },
    { value: "37|REPUBBLICA DI SAN MARINO|S", text: "REPUBBLICA DI SAN MARINO" },
    { value: "63|REPUBBLICA DOMINICANA|X", text: "REPUBBLICA DOMINICANA" },
    { value: "94|REPUBBLICA FED.DI GERMANIA|X", text: "REPUBBLICA FED.DI GERMANIA" },
    { value: "16|REPUBBLICA POPOLARE CINESE|S", text: "REPUBBLICA POPOLARE CINESE" },
    { value: "78|REPUBBLICA SUDAFRICANA|S", text: "REPUBBLICA SUDAFRICANA" },
    { value: "247|REUNION|X", text: "REUNION" },
    { value: "61|ROMANIA|S", text: "ROMANIA" },
    { value: "151|RUANDA|X", text: "RUANDA" },
    { value: "262|RUSSIA|S", text: "RUSSIA" },
    { value: "254|S.ELENA|X", text: "S.ELENA" },
    { value: "166|SAHARA OCCIDENTALE|X", text: "SAHARA OCCIDENTALE" },
    { value: "293|SAINT BARTHELEMY|X", text: "SAINT BARTHELEMY" },
    { value: "199|SAINT LUCIA|S", text: "SAINT LUCIA" },
    { value: "191|SALOMONE|X", text: "SALOMONE" },
    { value: "131|SAMOA OCCIDENTALE|X", text: "SAMOA OCCIDENTALE" },
    { value: "187|SAO TOME' E PRINCIPE|X", text: "SAO TOME' E PRINCIPE" },
    { value: "189|SEICELLE|S", text: "SEICELLE" },
    { value: "152|SENEGAL|X", text: "SENEGAL" },
    { value: "289|SERBIA|X", text: "SERBIA" },
    { value: "243|SHARJAH|X", text: "SHARJAH" },
    { value: "153|SIERRA LEONE|X", text: "SIERRA LEONE" },
    { value: "147|SINGAPORE|S", text: "SINGAPORE" },
    { value: "294|SINT MAARTEN (DUTCH PART)|X", text: "SINT MAARTEN (DUTCH PART)" },
    { value: "65|SIRIA|X", text: "SIRIA" },
    { value: "276|SLOVACCHIA|S", text: "SLOVACCHIA" },
    { value: "260|SLOVENIA|S", text: "SLOVENIA" },
    { value: "66|SOMALIA|X", text: "SOMALIA" },
    { value: "67|SPAGNA|S", text: "SPAGNA" },
    { value: "85|SRI LANKA|X", text: "SRI LANKA" },
    { value: "195|ST. KITTS E NEVIS|X", text: "ST. KITTS E NEVIS" },
    { value: "222|ST. MARTIN SETTENTRIONALE|X", text: "ST. MARTIN SETTENTRIONALE" },
    { value: "248|ST. PIERRE E MIQUELON|X", text: "ST. PIERRE E MIQUELON" },
    { value: "69|STATI UNITI D'AMERICA|S", text: "STATI UNITI D'AMERICA" },
    { value: "70|SUDAN|X", text: "SUDAN" },
    { value: "124|SURINAME|X", text: "SURINAME" },
    { value: "286|SVALBARD E JAN MAYEN ISOLE|X", text: "SVALBARD E JAN MAYEN ISOLE" },
    { value: "68|SVEZIA|S", text: "SVEZIA" },
    { value: "71|SVIZZERA|S", text: "SVIZZERA" },
    { value: "138|SWAZILAND - NGWANE|X", text: "SWAZILAND - NGWANE" },
    { value: "272|TAGIKISTAN|X", text: "TAGIKISTAN" },
    { value: "57|TANZANIA|X", text: "TANZANIA" },
    { value: "245|TERRIT.BRIT.OCC.|X", text: "TERRIT.BRIT.OCC." },
    { value: "183|TERRITORI FRANCESI DEL SUD|X", text: "TERRITORI FRANCESI DEL SUD" },
    { value: "180|TERRITORIO ANTARTICO BRITANNICO|X", text: "TERRITORIO ANTARTICO BRITANNICO" },
    { value: "72|THAILANDIA|X", text: "THAILANDIA" },
    { value: "287|TIMOR|X", text: "TIMOR" },
    { value: "155|TOGO|X", text: "TOGO" },
    { value: "236|TOKELAU|X", text: "TOKELAU" },
    { value: "162|TONGA|X", text: "TONGA" },
    { value: "120|TRINIDAD E TOBAGO|X", text: "TRINIDAD E TOBAGO" },
    { value: "229|TRISTAN DE CUNHA|S", text: "TRISTAN DE CUNHA" },
    { value: "75|TUNISIA|X", text: "TUNISIA" },
    { value: "76|TURCHIA|S", text: "TURCHIA" },
    { value: "273|TURKMENISTAN|X", text: "TURKMENISTAN" },
    { value: "210|TURKS E CAICOS|N", text: "TURKS E CAICOS" },
    { value: "193|TUVALU|X", text: "TUVALU" },
    { value: "263|UCRAINA|X", text: "UCRAINA" },
    { value: "132|UGANDA|X", text: "UGANDA" },
    { value: "244|UMM AL QAIWAIN|X", text: "UMM AL QAIWAIN" },
    { value: "77|UNGHERIA|S", text: "UNGHERIA" },
    { value: "80|URUGUAY|S", text: "URUGUAY" },
    { value: "271|UZBEKISTAN|X", text: "UZBEKISTAN" },
    { value: "121|VANUATU|X", text: "VANUATU" },
    { value: "81|VENEZUELA|X", text: "VENEZUELA" },
    { value: "221|VERGINI AMERICANE (ISOLE)|X", text: "VERGINI AMERICANE (ISOLE)" },
    { value: "62|VIETNAM|X", text: "VIETNAM" },
    { value: "196|VINCENT E GRENADINE|S", text: "VINCENT E GRENADINE" },
    { value: "218|WALLIS E FUTUNA|X", text: "WALLIS E FUTUNA" },
    { value: "42|YEMEN|X", text: "YEMEN" },
    { value: "58|ZAMBIA|X", text: "ZAMBIA" },
    { value: "73|ZIMBABWE|X", text: "ZIMBABWE" }
];
