<?php header('content-type: application/json; charset=utf-8'); ?>
{"esito":"ok","esitiRicerca":[
{"data":"29/04/2016",
"desc":"340 /3214828&#160;",
"idtipo":"CEL",
"tipo":"Ricariche cellulari/TV",
"stato":"Inserito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=19253763&tipoDisposizione=CEL",
"importo":"2,00 &euro;&#160;",
"annullabile":true,
"copiabile":true,
"param":"&numeroCRO=19253763&tipoDisposizione=CEL",
"data-key":"20160429000000",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-documenti\"></i ></a>",
"annulla":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-alert_error_fill\"></i ></a>"},
{"data":"22/11/2015&#160;",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-documenti\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-documenti\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-documenti\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/10/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"21/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/07/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
},
{"data":"22/11/2015",
"desc":"Pasti per un giorno 4 bambini&#160;",
"idtipo":"BFB","tipo":"Bollettini postali",
"stato":"Eseguito&#160;",
"info":"/webankpri/banking/webank/WsStatoDispDetailedJson.jsp?d=0&numeroCRO=20435568&tipoDisposizione=BFB",
"importo":"10,00 &euro;&#160;",
"annullabile":false,
"copiabile":true,
"param":"&numeroCRO=20435568&tipoDisposizione=BFB",
"data-key":"20151122165638",
"dettaglio":"<a href=\"#1\" class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-zoom_piu_filled\"></i ></a>",
"copia":"<a href=\"#1\"class=\"no-underline btn-icon\"><i class=\"icon icon-2x icon icon-copy\"></i ></a>",
"annulla":"<i class=\"icon icon-2x icon icon-alert_error_fill disabled\"></i >"
}


]}

