<?php
header('content-type: application/json; charset=utf-8');

$nconto = $_GET["numeroConto"];
$bftot = "5000.00";
$bfLibero = "4000.00";
if ($nconto == "2") {
	$bfLibero = "5000.00";
}
if ($nconto == "3") {
	$bfLibero = "0.00";
	$bftot = "0.00";
}

if ($nconto == "4")
{
	$bfLibero = "0.00";
	$bftot = "0.00";
	
}

?>{
	"listaObiettivi": [{
            "conto": "<?php print($nconto); ?>",
            "obiettivi":  [ <?php if ($nconto == "1") { ?>
                {
                    "banca": 1,
                    "causaleBonifico": "bonifico per obiettivo condiviso <<1D94WLU4U3C>>",
                    "codiceCondivisione": "9V95Z32NO8",
                    "codiceProdotto": "5",
                    "colore": 3,
                    "coloreHEX": "800000",
                    "coloreRGB": "128,0,0",
                    "condiviso": false,
                    "crowdMonetizzato": 0,
                    "crowdRisparmiato": 0,
                    "deviceName": "",
                    "figli": [],
                    "figlio": false,
                    "filialeConto": "00000",
                    "ibanUtente": "",
                    "id": 1442,
                    "idUtente": "0022123",
                    "imgProdotto": "/img/ret/categobi/shopping/ldpi.png",
                    "importoMaturato": 100,
                    "importoObiettivo": 1000,
                    "intestazioneUtente": "",
                    "modificabile": true,
                    "monetizzazioni": [],
                    "nazioneUtente": "",
                    "nomeObiettivo": "www",
                    "note": "",
                    "notificheImp": 0,
                    "notificheScad": 100,
                    "numeroConto": "0000066117",
                    "numeroErosioni": 0,
                    "prodotto": null,
                    "scadenza": "29/06/2014",
                    "stato": "S",
                    "tipologia": "LIB",
                    "tms_ins": "13/05/2014",
                    "tms_upd": "01/07/2014",
                    "totMonetizzazioniEsterne": 0,
                    "valutaConto": "EUR"
                },
                {
                    "banca": 1,
                    "causaleBonifico": "bonifico per obiettivo condiviso <<13ENYY5DAJ1>>",
                    "codiceCondivisione": "1N3LU9IWDQL",
                    "codiceProdotto": "4",
                    "colore": 1,
                    "coloreHEX": "ffa500",
                    "coloreRGB": "255,165,0",
                    "condiviso": true,
                    "crowdMonetizzato": 0,
                    "crowdRisparmiato": 0,
                    "deviceName": "",
                    "figli": [
                        {
                            "banca": 1,
                            "causaleBonifico": "bonifico per obiettivo condiviso <<2GOZWHQMBV0/3P3>>",
                            "codiceCondivisione": "1N5L3IOBP1N/5VZ",
                            "colore": 1,
                            "filiale": "00000",
                            "id": null,
                            "idPadre": 1447,
                            "importoPromesso": 1,
                            "intestazioneContribuente": "MARCO POMPEO PRADA",
                            "monetizzazioni": [],
                            "numeroConto": "0000003540",
                            "progressivo": 1,
                            "sommaMonetizzazioni": 0,
                            "stato": "I",
                            "tms_ins": "16/07/2014",
                            "tms_upd": "16/07/2014",
                            "userContribuente": "0077963",
                            "valuta": "EUR"
                        }
                    ],
                    "figlio": false,
                    "filialeConto": "00000",
                    "ibanUtente": "IT34Y0558401600000000066117",
                    "id": 1447,
                    "idUtente": "0022123",
                    "imgProdotto": "/img/ret/categobi/automoto/ldpi.png",
                    "importoMaturato": 1,
                    "importoObiettivo": 3500,
                    "intestazioneUtente": "PAJARDI PAOLO DANIELE",
                    "modificabile": true,
                    "monetizzazioni": [],
                    "nazioneUtente": "ITALIA",
                    "nomeObiettivo": "motorello",
                    "note": "",
                    "notificheImp": 0,
                    "notificheScad": 0,
                    "numeroConto": "0000066117",
                    "numeroErosioni": 0,
                    "prodotto": null,
                    "scadenza": "20/09/2014",
                    "stato": "I",
                    "tipologia": "LIB",
                    "tms_ins": "29/05/2014",
                    "tms_upd": "01/07/2014",
                    "totMonetizzazioniEsterne": 0,
                    "valutaConto": "EUR"
                },
                {
                    "banca": 1,
                    "causaleBonifico": "bonifico per obiettivo condiviso <<26SJPKWFH1S>>",
                    "codiceCondivisione": "9V95Z32NT9",
                    "codiceProdotto": "1",
                    "colore": 1,
                    "coloreHEX": "ffa500",
                    "coloreRGB": "255,165,0",
                    "condiviso": true,
                    "crowdMonetizzato": 0,
                    "crowdRisparmiato": 0,
                    "deviceName": "",
                    "figli": [],
                    "figlio": false,
                    "filialeConto": "00000",
                    "ibanUtente": "IT34Y0558401600000000066117",
                    "id": 1460,
                    "idUtente": "0022123",
                    "imgProdotto": "/img/ret/categobi/viaggi/ldpi.png",
                    "importoMaturato": 0,
                    "importoObiettivo": 10,
                    "intestazioneUtente": "PAJARDI PAOLO DANIELE",
                    "modificabile": true,
                    "monetizzazioni": [],
                    "nazioneUtente": "ITALIA",
                    "nomeObiettivo": "viaggio 1",
                    "note": "",
                    "notificheImp": 0,
                    "notificheScad": 0,
                    "numeroConto": "0000066117",
                    "numeroErosioni": 0,
                    "prodotto": null,
                    "scadenza": "16/07/2015",
                    "stato": "I",
                    "tipologia": "LIB",
                    "tms_ins": "15/07/2014",
                    "tms_upd": "15/07/2014",
                    "totMonetizzazioniEsterne": 0,
                    "valutaConto": "EUR"
                }
				<?php } ?>
				
				
				<?php if ($nconto == "4") { ?>
                {
                    "banca": 1,
                    "causaleBonifico": "bonifico per obiettivo condiviso <<1D94WLU4U3C>>",
                    "codiceCondivisione": "9V95Z32NO8",
                    "codiceProdotto": "5",
                    "colore": 3,
                    "coloreHEX": "800000",
                    "coloreRGB": "128,0,0",
                    "condiviso": false,
                    "crowdMonetizzato": 0,
                    "crowdRisparmiato": 0,
                    "deviceName": "",
                    "figli": [],
                    "figlio": false,
                    "filialeConto": "00000",
                    "ibanUtente": "",
                    "id": 1442,
                    "idUtente": "0022123",
                    "imgProdotto": "/img/ret/categobi/shopping/ldpi.png",
                    "importoMaturato": 0,
                    "importoObiettivo": 1000,
                    "intestazioneUtente": "",
                    "modificabile": true,
                    "monetizzazioni": [],
                    "nazioneUtente": "",
                    "nomeObiettivo": "www",
                    "note": "",
                    "notificheImp": 0,
                    "notificheScad": 100,
                    "numeroConto": "0000066117",
                    "numeroErosioni": 0,
                    "prodotto": null,
                    "scadenza": "29/06/2014",
                    "stato": "S",
                    "tipologia": "LIB",
                    "tms_ins": "13/05/2014",
                    "tms_upd": "01/07/2014",
                    "totMonetizzazioniEsterne": 0,
                    "valutaConto": "EUR"
                },
                {
                    "banca": 1,
                    "causaleBonifico": "bonifico per obiettivo condiviso <<13ENYY5DAJ1>>",
                    "codiceCondivisione": "1N3LU9IWDQL",
                    "codiceProdotto": "4",
                    "colore": 1,
                    "coloreHEX": "ffa500",
                    "coloreRGB": "255,165,0",
                    "condiviso": true,
                    "crowdMonetizzato": 0,
                    "crowdRisparmiato": 0,
                    "deviceName": "",
                    "figli": [
                        {
                            "banca": 1,
                            "causaleBonifico": "bonifico per obiettivo condiviso <<2GOZWHQMBV0/3P3>>",
                            "codiceCondivisione": "1N5L3IOBP1N/5VZ",
                            "colore": 1,
                            "filiale": "00000",
                            "id": null,
                            "idPadre": 1447,
                            "importoPromesso": 1,
                            "intestazioneContribuente": "MARCO POMPEO PRADA",
                            "monetizzazioni": [],
                            "numeroConto": "0000003540",
                            "progressivo": 1,
                            "sommaMonetizzazioni": 0,
                            "stato": "I",
                            "tms_ins": "16/07/2014",
                            "tms_upd": "16/07/2014",
                            "userContribuente": "0077963",
                            "valuta": "EUR"
                        }
                    ],
                    "figlio": false,
                    "filialeConto": "00000",
                    "ibanUtente": "IT34Y0558401600000000066117",
                    "id": 1447,
                    "idUtente": "0022123",
                    "imgProdotto": "/img/ret/categobi/automoto/ldpi.png",
                    "importoMaturato": 0,
                    "importoObiettivo": 3500,
                    "intestazioneUtente": "PAJARDI PAOLO DANIELE",
                    "modificabile": true,
                    "monetizzazioni": [],
                    "nazioneUtente": "ITALIA",
                    "nomeObiettivo": "motorello",
                    "note": "",
                    "notificheImp": 0,
                    "notificheScad": 0,
                    "numeroConto": "0000066117",
                    "numeroErosioni": 0,
                    "prodotto": null,
                    "scadenza": "20/09/2014",
                    "stato": "I",
                    "tipologia": "LIB",
                    "tms_ins": "29/05/2014",
                    "tms_upd": "01/07/2014",
                    "totMonetizzazioniEsterne": 0,
                    "valutaConto": "EUR"
                },
                {
                    "banca": 1,
                    "causaleBonifico": "bonifico per obiettivo condiviso <<26SJPKWFH1S>>",
                    "codiceCondivisione": "9V95Z32NT9",
                    "codiceProdotto": "1",
                    "colore": 1,
                    "coloreHEX": "ffa500",
                    "coloreRGB": "255,165,0",
                    "condiviso": true,
                    "crowdMonetizzato": 0,
                    "crowdRisparmiato": 0,
                    "deviceName": "",
                    "figli": [],
                    "figlio": false,
                    "filialeConto": "00000",
                    "ibanUtente": "IT34Y0558401600000000066117",
                    "id": 1460,
                    "idUtente": "0022123",
                    "imgProdotto": "/img/ret/categobi/viaggi/ldpi.png",
                    "importoMaturato": 0,
                    "importoObiettivo": 10,
                    "intestazioneUtente": "PAJARDI PAOLO DANIELE",
                    "modificabile": true,
                    "monetizzazioni": [],
                    "nazioneUtente": "ITALIA",
                    "nomeObiettivo": "viaggio 1",
                    "note": "",
                    "notificheImp": 0,
                    "notificheScad": 0,
                    "numeroConto": "0000066117",
                    "numeroErosioni": 0,
                    "prodotto": null,
                    "scadenza": "16/07/2015",
                    "stato": "I",
                    "tipologia": "LIB",
                    "tms_ins": "15/07/2014",
                    "tms_upd": "15/07/2014",
                    "totMonetizzazioniEsterne": 0,
                    "valutaConto": "EUR"
                }
				<?php } ?>
				
				
            ]
        }
    ],
	"capitaleRisparmiato": 5000,
	"capitaleRisparmiatoFormat": "<?php print($bftot); ?>",
	"capitaleRisparmiatoParteLibera": 4000,
	"capitaleRisparmiatoParteLiberaFormat": "<?php print($bfLibero); ?>",
	"esito": "ok"
}
