#!/bin/bash
# PER RISOLVERE PERMISSION DENIED USARE: chmod +x version_html_statico

echo -n "Hai generato lo statico prima di far partire lo script? (y/n) "
read REPLY
if [[ $REPLY =~ ^[y]$ ]]
then

  current_time=$(date "+%y%m%d_%H%M")

  # prima cartella
  newpath="/Users/martapetrella/Documents/HTML_STATICO"
  newname="html_statico_$current_time"
  newfile="$newname.zip"

  zip -vr "$newfile" html_statico/ changelog.html  -x "*.DS_Store" -qq
  mv "$newfile" "$newpath"

 DIR="/Users/martapetrella/GDrive_Dechit.it/WeBank/YoubBusinessweb/HTML_STATICO(versionato)"
 if [ -d "$DIR" ]; then
   cp "$newpath/$newfile" "$DIR"
   echo "$newname copied!"
 fi

else
  echo "Allora vai e torna! :D "
fi
echo "\n"
