export const initialValues = {
    "nome": "Giovanni",
    "cognome": "Cosmi",
    "nascita": "01-01-1980",
    "comune_nascita": "MILANO",
    "tipo_indirizzo_residenza": "CORSO",
    "nome_indirizzo_residenza": "MAGENTA",
    "numero_indirizzo_residenza": "1",
    "provincia_residenza": "MILANO",
    "comune_residenza": "MILANO",
    "cond_generali": "",
    "disposizioni": "",
    "doc_feq": "",
    "doc_pec": "",
    "cond_feq": "",
    "cond_pec": "",
    "info_precontrattuale_cc": "",
    "info_precontrattuale_dt": "",
    "info_precontrattuale_si": "",
    "doc_privacy": "",
    "doc_antiriciclaggio": "",
    "doc_cond_econ": "",
    "doc_recesso": "",
    "doc_fatca": "",
    "doc_dt": "",
    "codice-otp": ""
};