export const initialValues = {
    /* Step 1 */
    "nome": "Giovanni",
    "cognome": "Cosmi",
    "nascita": "01-01-1980",
    "sesso": "M",
    "codicefiscale": "CSMGNN80A01F205T",
    "email": "giovanni.cosmi@example.com",
    "prefisso": "0039",
    "numero": "3331234567",
    "operatore": "Vodafone",
    /* Step 2 */
    "cittadinanza": "ITALIA",
    "paese_nascita": "ITALIA",
    "provincia_nascita": "MILANO",
    "comune_nascita": "MILANO",
    "tipo_documento": "CARTA DI IDENTITA' CARTACEA",
    "numero_documento": "AA123456",
    "paese_rilascio": "ITALIA",
    "provincia_rilascio": "MILANO",
    "comune_rilascio": "MILANO",
    "data_rilascio": "01-01-2010",
    "data_scadenza": "01-01-2020",
    "tipo_indirizzo_residenza": "CORSO",
    "nome_indirizzo_residenza": "MAGENTA",
    "numero_indirizzo_residenza": "1",
    "provincia_residenza": "MILANO",
    "comune_residenza": "MILANO",
    "cap_residenza": "20123",
    /* Step 3 */
    "servizio-investimento": "Incluso",
    "deposito-titoli": "Incluso",
    /* Step 4 */
    "titolare": "Sì",
    "politicamente-esposto": "No",
    "scopo-rapporto-cc": "Risparmio",
    "scopo-rapporto-ct": "Investimento",
    "professione": "Libero professionista",
    "tipo-attivita": "Avvocato",
    "stato-svolgimento": "ITALIA",
    "provincia-svolgimento": "MILANO",
    "origine-patrimonio": "Reddito da lavoro",
    "pa-dichiarazione": "Nessuno",
    "pa-ovvero": "Nessuno",
    "conflitto-dichiarazione": "No",
    /* Step 6 */
    "identita_accertata": ""
};