// Variabili lingua IT - fabrix.xm@lombardiacom.it

tinyMCE.addToLang('',{
bold_desc : 'Grassetto',
italic_desc : 'Corsivo',
underline_desc : 'Sottolineato',
tooltip_desc : 'Tooltip',
striketrough_desc : 'Barrato',
justifyleft_desc : 'Allinea a sinistra',
justifycenter_desc : 'Allinea centrato',
justifyright_desc : 'Allinea a destra',
justifyfull_desc : 'Giustifica',
bullist_desc : 'Elenco puntato',
numlist_desc : 'Elenco numerato',
outdent_desc : 'Rientra',
indent_desc : 'Indenta',
undo_desc : 'Annulla',
redo_desc : 'Ripeti',
link_desc : 'Inserisci link',
unlink_desc : 'Elimina link',
litag_desc : 'Gestisci tag li',
image_desc : 'Inserisci immagine',
cleanup_desc : 'Pulisci il  codice',
theme_anchor_desc : 'Ancora',
theme_sub_desc : 'Pedice',
theme_sup_desc : 'Apice',
focus_alert : 'Una istanza dell\' editor deve essere selezionata prima di usare questo comando.',
edit_confirm : 'Vuoi usare la modalit\u00E0 WYSIWYG per questa textarea?',
insert_link_title : 'Inserisci/modifica link',
insert_litag_title : 'Gestisci gli attributi del tag LI',
insert : 'Inserisci',
update : 'Inserisci',
cancel : 'Cancella',
insert_link_url : 'Link URL',
insert_link_target : 'Target',
insert_link_target_same : 'Apri il link nella stessa finestra',
insert_link_target_blank : 'Apri il link in una nuova finestra',
insert_image_title : 'Inserisci/modifica immagine',
insert_image_src : 'URL immagine',
insert_image_alt : 'Descrizione dell\'immagine',
insert_link_style : 'Stile',
insert_link_rel : 'Tag rel',
insert_image_align : 'Stile allineamento',
insert_image_dimensions : 'Dimensioni',
insert_image_border : 'Bordo',
insert_image_vspace : 'Spaziatura verticale',
insert_image_hspace : 'Spaziatura orizzontale',
insert_anchor_title : 'Inserimento ancora',
insert_anchor_name : 'nome',
theme_insert_link_titlefield : 'Title',
theme_insert_litag_label : 'Label',
theme_code_title : 'Editor sorgente HTML',
theme_code_wordwrap : 'A capo automatico',
theme_code_desc : 'Editor HTML',
theme_charmap_title : 'Caratteri speciali',
theme_charmap_desc : 'Caratteri speciali',
insert_tooltip_title : 'Inserisci/modifica il tooltip',
insert_tooltip_textfield : 'Testo',
help_desc : 'Guida',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copia, Taglia e Incolla non sono disponibili in Mozilla e Firefox.\nVuoi maggiori dettegli su questo problema?',
popup_blocked : 'Spiacenti, un sistema di blocco popup ha impedito l\'apertura di una finestra necessaria per il funzionamento dell\'editor. Disabilita il blocco popup per questo sito se vuoi utilizzare tutte le funzionalit\u00E0.'
});
