<?php
   header("content-type: application/json; charset=utf-8");
   // Simula il tempo di esecuzione della chiamata
   // sleep(1);
?>{
    "data":[
        {
            "codicefida":"INVE0008",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Azionari Paese",
            "codiceisin":"LU0717749021",
            "rischio":"6",
            "perc5a":null,
            "nome":"Invesco China Focus Equity E Cap EUR",
            "perc1a":"-21.2038",
            "rating":"5",
            "codicecomparto":"I0070"
        },
        {
            "codicefida":"INCONTD",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Fondi Flessibili",
            "codiceisin":"LU0243957312",
            "rischio":"4",
            "perc5a":"46.5135",
            "nome":"Invesco Pan European High Income AQ Dis EUR",
            "perc1a":"-2.7392",
            "rating":"3",
            "codicecomparto":"I0106"
        },
        {
            "codicefida":"IN1340",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Fondi Flessibili",
            "codiceisin":"LU0794791011",
            "rischio":"4",
            "perc5a":null,
            "nome":"Invesco Pan European High Income R Cap EUR",
            "perc1a":"-3.4294",
            "rating":"4",
            "codicecomparto":"I0089"
        },
        {
            "codicefida":"INVCFEA$",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"USD",
            "nomecategoriabrating":"Azionari Paese",
            "codiceisin":"LU0717748643",
            "rischio":"6",
            "perc5a":null,
            "nome":"Invesco China Focus Equity A Cap $",
            "perc1a":"-20.8421",
            "rating":"1",
            "codicecomparto":"I0128"
        },
        {
            "codicefida":"PSEURBO",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Obb. Euro Governativi M/L Termine",
            "codiceisin":"LU0066341099",
            "rischio":"3",
            "perc5a":"44.4447",
            "nome":"Invesco Euro Bond A EUR",
            "perc1a":"-0.1125",
            "rating":"5",
            "codicecomparto":"I0204"
        },
        {
            "codicefida":"INGCBYAH",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Obb. Intern. Corporate Investment Grade",
            "codiceisin":"LU0432616570",
            "rischio":"3",
            "perc5a":"27.8772",
            "nome":"Invesco Gl. Investment Grade Corp. Bond Acc AH EUR",
            "perc1a":"2.5595",
            "rating":"2",
            "codicecomparto":"I0155"
        },
        {
            "codicefida":"INGCBYA",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"USD",
            "nomecategoriabrating":"Obb. Intern. Corporate Investment Grade",
            "codiceisin":"LU0432616141",
            "rischio":"3",
            "perc5a":"65.1794",
            "nome":"Invesco Gl. Investment Grade Corp. Bond A DisY $",
            "perc1a":"0.5016",
            "rating":"4",
            "codicecomparto":"I0156"
        },
        {
            "codicefida":"INGIGAD",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"USD",
            "nomecategoriabrating":"Obb. Intern. Corporate Investment Grade",
            "codiceisin":"LU0482542841",
            "rischio":"3",
            "perc5a":"64.7767",
            "nome":"Invesco Gl. Investment Grade Corp. Bond A DisM $",
            "perc1a":"0.1953",
            "rating":"3",
            "codicecomparto":"I0158"
        },
        {
            "codicefida":"PSLEISU",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"USD",
            "nomecategoriabrating":"Azionari Altri Settori",
            "codiceisin":"LU0052864419",
            "rischio":"6",
            "perc5a":"125.9037",
            "nome":"Invesco Global Leisure A $",
            "perc1a":"-3.8617",
            "rating":"5",
            "codicecomparto":"I0159"
        },
        {
            "codicefida":"INVF01",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"USD",
            "nomecategoriabrating":"Azionari Internazionali",
            "codiceisin":"LU0607512778",
            "rischio":"6",
            "perc5a":"84.7977",
            "nome":"Invesco Global Smaller Companies Equity A Cap $",
            "perc1a":"-1.6881",
            "rating":"1",
            "codicecomparto":"I0160"
        },
        {
            "codicefida":"INVF02",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"USD",
            "nomecategoriabrating":"Azionari Internazionali",
            "codiceisin":"LU0607512695",
            "rischio":"6",
            "perc5a":"84.8679",
            "nome":"Invesco Global Smaller Companies Equity A Dis $",
            "perc1a":"-1.6674",
            "rating":"4",
            "codicecomparto":"I0162"
        },
        {
            "codicefida":"IGSTRA",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"USD",
            "nomecategoriabrating":"Azionari Internazionali",
            "codiceisin":"LU0267984937",
            "rischio":"5",
            "perc5a":"93.9984",
            "nome":"Invesco Global Structured Equity A Dis $",
            "perc1a":"-8.4038",
            "rating":"3",
            "codicecomparto":"I0164"
        },
        {
            "codicefida":"INPEINA",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Azionari Europa",
            "codiceisin":"LU0267986122",
            "rischio":"5",
            "perc5a":"69.8598",
            "nome":"Invesco Pan European Eq. Income A Cap EUR",
            "perc1a":"-10.3576",
            "rating":"2",
            "codicecomparto":"I0180"
        },
        {
            "codicefida":"INPEINDI",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Azionari Europa",
            "codiceisin":"LU0267986049",
            "rischio":"5",
            "perc5a":"69.9836",
            "nome":"Invesco Pan European Eq. Income A Dis EUR",
            "perc1a":"-10.3663",
            "rating":"5",
            "codicecomparto":"I0181"
        },
        {
            "codicefida":"IV1673",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Azionari Europa",
            "codiceisin":"LU0642795305",
            "rischio":"6",
            "perc5a":null,
            "nome":"Invesco Pan European Focus Equity Cap A EUR",
            "perc1a":"-14.3582",
            "rating":"4",
            "codicecomparto":"I0182"
        },
        {
            "codicefida":"INV1407",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Azionari Europa",
            "codiceisin":"LU0717747678",
            "rischio":"6",
            "perc5a":null,
            "nome":"Invesco Pan European Focus Equity A Dis EUR",
            "perc1a":"-14.3356",
            "rating":"1",
            "codicecomparto":"I0183"
        },
        {
            "codicefida":"INCONT",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Fondi Flessibili",
            "codiceisin":"LU0243957239",
            "rischio":"4",
            "perc5a":"46.539",
            "nome":"Invesco Pan European High Income A Cap. EUR",
            "perc1a":"-2.7846",
            "rating":"2",
            "codicecomparto":"I0213"
        },
        {
            "codicefida":"ISTRUCA",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Azionari Europa",
            "codiceisin":"LU0119750205",
            "rischio":"5",
            "perc5a":"73.1781",
            "nome":"Invesco Pan European Structured Eq. A EUR",
            "perc1a":"-5.5218",
            "rating":"4",
            "codicecomparto":"I0214"
        },
        {
            "codicefida":"INVE15",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"EUR",
            "nomecategoriabrating":"Azionari Europa",
            "codiceisin":"LU0482499141",
            "rischio":"5",
            "perc5a":"73.2306",
            "nome":"Invesco Pan European Structured Eq. Dis A EUR",
            "perc1a":"-5.516",
            "rating":"3",
            "codicecomparto":"I0186"
        },
        {
            "codicefida":"INVE0009",
            "codicesocieta":"108",
            "casadigestione":"Invesco Global Asset Mgmt Ltd",
            "fondosicav":"S",
            "divisa":"USD",
            "nomecategoriabrating":"Azionari Paese",
            "codiceisin":"LU0717749294",
            "rischio":"6",
            "perc5a":null,
            "nome":"Invesco China Focus Equity R Cap $",
            "perc1a":"-21.3956",
            "rating":"5",
            "codicecomparto":"I0077"
        }
    ]
}