"5": {"nome":"Algebris Ucits Funds plc","img_old":"/wscmn/img/ret/img_or_S-algebris.gif","img":"/fe/img/lgsoc_algebris.png"},
"10":{"nome":"Allianz Global Investors Lux.","img_old":"/wscmn/img/ret/img_or_S-allianz.gif","img":"/fe/img/lgsoc_allianz.png"},
"15":{"nome":"Amundi Funds", "img_old":"/wscmn/img/ret/img_or_amundi.gif","img":"/fe/img/lgsoc_amundi.png"},
"20":{"nome":"Anima Asset Management ltd", "img_old":"/wscmn/img/ret/img_or_prima_new.gif","img":"/fe/img/lgsoc_prima_new.png"},
"30":{"nome":"Anima Sgr Spa", "img_old":"/wscmn/img/ret/img_or_S-anima_new.gif" ,"img":"/fe/img/lgsoc_anima_new.png"},
"40":{"nome":"BlackRock (Luxembourg) S.A.","img_old":"/wscmn/img/ret/img_or_S-Blackrock.gif","img":"/fe/img/lgsoc_blackrock.png"},
"50":{"nome":"Carmignac Gestion","img_old":"/wscmn/img/ret/img_or_S-carmignac_fondi.gif","img":"/fe/img/lgsoc_carmignac_fondi.png"},
"60":{"nome":"Carmignac Portfolio Sicav", "img_old":"/wscmn/img/ret/img_or_S-carmignac_port.gif","img":"/fe/img/lgsoc_carmignac_port.png"},
"65":{"nome":"Columbia Threadneedle","img_old":"/wscmn/img/ret/img_or_S-threadneedle.gif","img":"/fe/img/lgsoc_threadneedle.png"},
"70":{"nome":"DWS", "img_old":"/wscmn/img/ret/img_or_S-dws.gif","img":"/fe/img/lgsoc_dws.png"},
"80":{"nome":"Epsilon Sgr Spa","img_old":"/wscmn/img/ret/img_or_S-epsilon.gif","img":"/fe/img/lgsoc_epsilon.png"},
"90":{"nome":"Etica Sgr Spa","img_old":"/wscmn/img/ret/img_or_S-etica.gif","img":"/fe/img/lgsoc_etica.png"},
"100":{"nome":"Eurizon Capital Sgr Spa","img_old":"/wscmn/img/ret/img_or_S-Eurizon.gif","img":"/fe/img/lgsoc_eurizon.png"},
"110":{"nome":"Fidelity Investments Lux. S.A.","img_old":"/wscmn/img/ret/img_or_S-fidelity.gif","img":"/fe/img/lgsoc_fidelity.png"},
"120":{"nome":"Franklin Templeton Inv. Sicav","img_old":"/wscmn/img/ret/img_or_S-Franklin.gif","img":"/fe/img/lgsoc_franklin.png"},
"125":{"nome":"GAM I.M. Ltd-Julius Baer Funds","img_old":"/wscmn/img/ret/img_or_JB.gif","img":"/fe/img/lgsoc_jb.png"},
"130":{"nome":"HSBC Global Investment Funds","img_old":"/wscmn/img/ret/img_or_S_hsbc.gif","img":"/fe/img/lgsoc_hsbc.png"},
"140":{"nome":"Invesco Fund","img_old":"/wscmn/img/ret/img_or_S-invesco.gif","img":"/fe/img/lgsoc_invesco.png"},
"160":{"nome":"JPMorgan Funds","img_old":"/wscmn/img/ret/img_or_S-JPMorganAM.gif","img":"/fe/img/lgsoc_jpmorganam.png"},
"170":{"nome":"JPMorgan Investment Funds","img_old":"/wscmn/img/ret/img_or_S-JPMinv.gif","img":"/fe/img/lgsoc_jpminv.png"},
"150":{"nome":"Janus Capital Funds plc","img_old":"/wscmn/img/ret/img_or_S-janus.gif","img":"/fe/img/lgsoc_janus.png"},
"180":{"nome":"Legg Mason Global Asset Mngt","img_old":"/wscmn/img/ret/img_or_S_legg_mason.gif","img":"/fe/img/lgsoc_legg_mason.png"},
"190":{"nome":"Lombard Odier Funds","img_old":"/wscmn/img/ret/img_or_S_lombard_odier.gif","img":"/fe/img/lgsoc_lombard_odier.png"},
"200":{"nome":"M&G Global","img_old":"/wscmn/img/ret/img_or_MG.gif","img":"/fe/img/lgsoc_mg.png"},
"210":{"nome":"Morgan Stanley Investment Fund","img_old":"/wscmn/img/ret/img_or_S-morganstanley.gif","img":"/fe/img/lgsoc_morganstanley.png"},
"215":{"nome":"NN(L) Investment Funds","img_old":"/wscmn/img/ret/img_or_S_nn.gif","img":"/fe/img/lgsoc_nn.png"},
"220":{"nome":"Pictet Funds (Europe) S.A.","img_old":"/wscmn/img/ret/img_or_S-pictet.gif","img":"/fe/img/lgsoc_pictet.png"},
"230":{"nome":"Pimco Funds Gl.Inv. Series Plc","img_old":"/wscmn/img/ret/img_or_S-pimco.gif","img":"/fe/img/lgsoc_pimco.png"},
"235":{"nome":"Raiffeisen Capital Management","img_old":"/wscmn/img/ret/img_or_S-raiffeisen.gif","img":"/fe/img/lgsoc_raffeisen.png"},
"240":{"nome":"Schroder Int. Selection Fund","img_old":"/wscmn/img/ret/img_or_S-schroeder.gif","img":"/fe/img/lgsoc_schroders.png"}