<!-- BOTTONE COLOR VERDE PIENO SU BIANCO OVER NERO -->
	<a class="btn-grlit">LOREM IPSUM</a>
<!-- FINE BOTTONE COLOR VERDE PIENO  SU BIANCO  OVER NERO-->

<!--SE &egrave; UN SUBMIT DI FORM- USARE BUTTON TYPE="SUBMIT"->
<!--SE SI VUOLE FONT_SIZE 14 AGGIUNGERE CLASSE btn-fs14 -->
<!--SE SI VUOLE FONT_SIZE 24 AGGIUNGERE CLASSE btn-fs24 -->